### PR TITLE
Fixed feature detection for E switches with 500 software

### LINKED ISSUE #2615: Incorrect Feature detection on E switches with 500 software
500 software changed of switch description fields. It cause incorrect feature detection for this features.

### PR DESCRIPTION
**Pull request by niksv**
Closes #2615

---
This change is [Reviewable](https://reviewable.io/reviews/telstra/open-kilda/2616)

### CODE REVIEW

File: services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/AbstractFeature.java [hunk 1]
```diff
@@ -20,9 +20,13 @@
 import net.floodlightcontroller.core.IOFSwitch;
 
 import java.util.Optional;
+import java.util.regex.Pattern;
 
 public abstract class AbstractFeature {
     protected static final String MANUFACTURER_NICIRA = "Nicira, Inc.";
+    protected static final String E_SWITCH_MANUFACTURER_DESCRIPTION = "E";
+    protected static final Pattern E_SWITCH_HARDWARE_DESCRIPTION_REGEX = Pattern.compile("^WB5\\d{3}-E$");
+    protected static final String CENTEC_MANUFACTURED = "Centec";
```
Comment (timofei-durakov) [inline services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/AbstractFeature.java]: nit: manufacturer looks better, and aligned with nicira:-P
