### PR TITLE
Refactor and fix atdd-staging

### LINKED ISSUE #2004: fix Atdd-staging
Atdd-staging has run a bit out of date and some tests are not valid. This needs to be fixed

### PR DESCRIPTION
**Pull request by ylobankov**
Closes #2004.

### CODE REVIEW

File: services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/HealthCheckSteps.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
+/* Copyright 2018 Telstra Open Source
```
Comment (andriidovhan) [inline services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/HealthCheckSteps.java]: 2018-2019

Comment (andriidovhan) [reply services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/HealthCheckSteps.java]: the same issue in all new created  files

Comment (ylobankov) [reply services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/HealthCheckSteps.java]: Fixed.
