### PR TITLE
resuse bandwidth during Y create

### LINKED ISSUE #4965: Can't create Y-flow with bandwidth=available bandwidth
**Steps to reproduce:**
1. Find endpoints for Y flow which must have shared path. For emample
```
A ----B ---- C
      | 
      D
```
Where A is shared endpoint of Y flow, C and D - two other endpoints. A-B shared path
2. Find available bandwidth of shared path (A-B). Let in be X.
3. Create Y flow on these endpoints with bandwidth X via API `POST /v2/y-flows`

**Expected result:**
Flow was created

**Actual result:**
Flow was not created because "not enough bandwidth"

NOTE: I found variable `sharedBandwidthGroupId` in code, I guess Kilda use for shared path part to do not subtract bandwidth from ISL twice. Maybe it can help fix the bug

### PR DESCRIPTION
**Pull request by pablomuri**
Closes #4965

### CODE REVIEW

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java [hunk 1]
```diff
@@ -65,18 +65,16 @@ public AvailableNetwork getAvailableNetwork(Flow flow, Collection<PathId> reuseP
...
-                                    pathId, flow.getBandwidth(), flow.getEncapsulationType())
-                                    .forEach(link -> addIslAsEdge(link, network));
-                        });
+            if (!flow.isIgnoreBandwidth()) {
+                if (flow.getYFlowId() != null) {
+                    Collection<PathId> flowPaths =
+                            flowPathRepository.findPathIdsBySharedBandwidthGroupId(flow.getYFlowId());
+                    if (!flowPaths.isEmpty()) {
+                        reuseResources(flowPaths, flow, network);
+                    }
```
Comment (niksv) [inline src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java:74]: I know that it works, but this code looks like not very correct. If we are working with Y flow we ignore `reusePathsResources` parameter. And this looks incorrect from user point of view. 
If user use `reusePathsResources` collection then he expects that this paths will be ignored.

I think we have several options here:
1. collected shared paths of Y flow in FlowHs topology and call getAvailableNetwork with list of Y flow path list
2. add some other method getAvailableNetwork only for Y flows
3. rewrite getAvailableNetwork to use repositories for finding reusePathsResources, but I think it's not possible, because sometimes we need to force the method to do not use shared resources. For example we use it in reroute operation: 
[reusePathsResources](https://github.com/telstra/open-kilda/blob/37ce148c2e974d3840c3e9a92cb238850ff07a0d/src-java/flowhs-topology/flowhs-storm-
topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java#L113)

File: src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java [hunk 2]
```diff
@@ -151,6 +151,17 @@ public Optional<FlowPath> findByCookie(FlowSegmentCookie cookie) {
...
+    public Collection<PathId> findPathIdsBySharedBandwidthGroupId(String sharedBandwidthGroupId) {
+        return framedGraph().traverse(g -> g.V()
+                        .hasLabel(FlowPathFrame.FRAME_LABEL)
+                        .has(FlowPathFrame.SHARED_BANDWIDTH_GROUP_ID_PROPERTY, sharedBandwidthGroupId)
+                        .values(FlowPathFrame.PATH_ID_PROPERTY))
+                .getRawTraversal().toStream()
+                .map(pathId -> PathIdConverter.INSTANCE.toEntityAttribute((String) pathId))
+                .collect(Collectors.toList());
+    }
+
```
Comment (niksv) [inline src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java:164]: Could you please add unit test for this method?

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java (hunk 1 above)
Comment (pablomuri) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java:79]: Done. 
As discussed offline, I've joined both lists if it is YFlow instead of not using the reusePathResources.

File: src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java (hunk 2 above)
Comment (pablomuri) [reply src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java:164]: Done

File: src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepositoryTest.java [hunk 3]
```diff
@@ -394,6 +394,23 @@ public void shouldFindFlowPathIdsByFlowIds() {
         assertTrue(pathIds.contains(flowB.getReversePathId()));
     }
 
+    @Test
+    public void findPathIdsBySharedBandwidthGroupId() {
+        String sharedBandwidthGroupId = "";
```
Comment (niksv) [inline src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepositoryTest.java:399]: Just interesting: why groupId is empty string?

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java [hunk 4]
```diff
@@ -220,6 +220,167 @@ public void shouldBuildAvailableNetworkForFlowWithIgnoreBandwidthPaths() throws
         assertAvailableNetworkIsCorrect(isl, availableNetwork);
     }
 
+    @Test
+    public void shouldBuildAvailableNetworkReusingBandwidthFromYFlowAndReusePathResources() throws Exception {
+        String yFlowId = "y-flow-id";
+        Flow flow1 = Flow.builder()
+                .flowId("test-id")
+                .srcSwitch(Switch.builder().switchId(new SwitchId("1")).build())
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java:228]: we have a lot of constants in this class so you can reuse them if you want. For example 
`SWITCH_ID_1`

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java [hunk 5]
```diff
@@ -272,4 +433,14 @@ private static void assertAvailableNetworkIsCorrect(IslImmutableView isl, Availa
         assertNotNull(dst);
         assertEquals(1, dst.getIncomingLinks().size());
     }
+
+    private static void assertAvailableNetworkIsNotCorrect(IslImmutableView isl, AvailableNetwork availableNetwork) {
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java:437]: Wrong name of the method. Actually network is correct. Here you are checking that these is no ISL in available network

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java [hunk 6]
```diff
@@ -272,4 +433,14 @@ private static void assertAvailableNetworkIsCorrect(IslImmutableView isl, Availa
...
+        Node src = availableNetwork.getSwitch(isl.getSrcSwitchId());
+        assertNotNull(src);
+        assertEquals(0, src.getOutgoingLinks().size());
+
+        Node dst = availableNetwork.getSwitch(isl.getDestSwitchId());
+        assertNotNull(dst);
+        assertEquals(0, dst.getIncomingLinks().size());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java:444]: It's not quite correct. this assert is valid only for your test case. To make it more correct you need to go throw all 
```
src.getOutgoingLinks()
src.getIncomingLinks()
dst.getOutgoingLinks()
dst.getIncomingLinks()
```

And check that all of them has no ISL `isl`

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java (hunk 1 above)
Comment (pablomuri) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java]: Yes, much better. Even we can remove the if (!reusePaths.isEmpty()) since the reuseResources iterate over the Set, so if it is empty it doesn't iterate.

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java (hunk 4 above)
Comment (pablomuri) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java]: done

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java (hunk 6 above)
Comment (pablomuri) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java]: Done, checked it inside the test case

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java (hunk 5 above)
Comment (pablomuri) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java]: Done, checked it inside the test case

File: src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepositoryTest.java (hunk 3 above)
Comment (pablomuri) [reply src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepositoryTest.java]: just because my memory sometimes fails 😆 
fixed

**Review by niksv — APPROVED** [review]

**Comment by pkazlenka** [comment]
Created an autotest PR, that verifies this issue: https://github.com/telstra/open-kilda/pull/5034

**Review by dmitrii-beliakov — APPROVED** [review]

**Review by durgakako — APPROVED** [review]
