### PR TITLE
#769: implemented additional topology for read operations from neo4j. fixed getting all switches / ISLs

### LINKED ISSUE #769: Eliminate read operations from TER (switches, ISLs) - it takes too long
Create separate storm topology to perform simple read operations from DB for NB calls.

### PR DESCRIPTION
**Pull request by nikitacherevko**
Fixed loading all switches and all links lists.

Closes #769

### CODE REVIEW

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+
+    @Override
+    public void execute(Tuple input) {
+        final String streamId = input.getSourceStreamId();
+        final String correlationId = input.getString(1);
+        LOGGER.debug("Received request with correlationId: {}", correlationId);
+
+        try {
+            switch (StreamType.valueOf(streamId)) {
+                case READ:
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java]: as for me - this incorrect level of requests split. Requests should be splitted based on type of resources(ISL, Switch, Flow, etc) not kind of operation. Because most(or even all) operations in this topology will be "read"... it will increase size of this bolt to enormous values.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+    private List<SwitchInfoData> getSwitches(Session session) {
+        StatementResult result = session.run("MATCH (sw:switch) " +
+                        "RETURN " +
+                        "sw.name as name, " +
+                        "sw.address as address, " +
+                        "sw.hostname as hostname, " +
+                        "sw.description as description, " +
+                        "sw.controller as controller, " +
+                        "sw.state as state " +
+                        "order by sw.name");
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java]: why for we need order?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+                        "isl.src_switch as src_switch, " +
+                        "isl.src_port as src_port, " +
+                        "isl.dst_switch as dst_switch, " +
+                        "isl.dst_port as dst_port, " +
+                        "isl.speed as speed, " +
+                        "isl.max_bandwidth as max_bandwidth, " +
+                        "isl.latency as latency, " +
+                        "isl.available_bandwidth as available_bandwidth, " +
+                        "isl.status as status " +
+                        "order by isl.src_switch";
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java]: same here - why for we need order?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+    public void declareOutputFields(OutputFieldsDeclarer declarer) {
+        declarer.declare(new Fields("response", "correlationId"));
+    }
+
+    @Override
+    public void cleanup() {
+        driver.close();
+    }
+
+    private int parseValue(Value value) {
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/NeoBolt.java]: Should it be named as "parseIntValue"?
PS Looks like it can't handle numbers stored as strings... it is pity but we have them in DB.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/ResponseSplitterBolt.java [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+
+    @Override
+    public void prepare(Map stormConf, TopologyContext context, OutputCollector collector) {
+        this.collector = collector;
+    }
+
+    @Override
+    public void execute(Tuple input) {
+        try {
+            List<InfoData> responses = (List<InfoData>) input.getValue(0);
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/ResponseSplitterBolt.java]: `input.getValueByField(...)` is much safer than `input.getValue(0)` - it will not create problem when stream format being altered.

File: services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/ChunkedInfoMessage.java [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+import com.fasterxml.jackson.annotation.JsonProperty;
+import lombok.Getter;
+import org.openkilda.messaging.info.InfoData;
+import org.openkilda.messaging.info.InfoMessage;
+
+@Getter
+public class ChunkedInfoMessage extends InfoMessage {
+
+    @JsonProperty("total_items")
+    private int totalItems;
```
Comment (surabujin) [inline services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/ChunkedInfoMessage.java]: Why for we need totalItems if we already have "end stream marker"? (nextRequestId == null)

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java [hunk 7]
```diff
@@ -65,18 +62,18 @@
...
     private static final Logger logger = LoggerFactory.getLogger(FlowTopology.class);
 
-    private final Auth pathComputerAuth;
+    private final PathComputerAuth pathComputerAuth;
 
     public FlowTopology(LaunchEnvironment env) throws ConfigurationException {
         super(env);
-        pathComputerAuth = config.getPathComputerAuth();
-
+        pathComputerAuth = new PathComputerAuth(config.getNeo4jHost(), config.getNeo4jLogin(),
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java]: Why you don't use config, to produce this PathComputerAuth object?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 8]
```diff
@@ -0,0 +1,166 @@
...
+        super.prepare(stormConf, context, collector);
+    }
+
+
+    @Override
+    protected void handleInput(Tuple input) throws AbstractException {
+        LinksBaseRequest request = (LinksBaseRequest) input.getValueByField("request");
+        final String correlationId = input.getStringByField("correlationId");
+
+        LOGGER.debug("Received read request with correlationId {}", correlationId);
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: ... now we have a correlation-id logged into separate/extra field. So it shouldn't be here.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 9]
```diff
@@ -0,0 +1,166 @@
...
+        try (Session session = driver.session(request.isReadRequest() ? AccessMode.READ : AccessMode.WRITE)) {
+            List result = null;
+            if (request instanceof GetLinksRequest) {
+                result = getAllLinks(session);
+            } else {
+                LOGGER.warn("Received unsupported Links request: {}", correlationId);
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: unhandledInput() ?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+            }
+
+            LOGGER.debug("Processed read request with correlationId {}", correlationId);
+            getOutput().emit(Lists.newArrayList(result, correlationId));
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: you must pass "input" to keep request traking by storm.
Also you should use Fields object, to construct output tuple.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+                        + "isl.latency as latency, "
+                        + "isl.available_bandwidth as available_bandwidth, "
+                        + "isl.status as status";
+
+        StatementResult queryResults = session.run(q);
+        List<IslInfoData> results = new ArrayList<>();
+        for (Record record : queryResults.list()) {
+            LOGGER.debug("Reading record... {}", record);
+            // max_bandwidth not used in IslInfoData
+            PathNode src = new PathNode();
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: Maybe we should have corresponding constructor in PathNode object?..

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+            src.setSwitchId(record.get("src_switch").asString());
+            src.setPortNo(parseIntValue(record.get("src_port")));
+            src.setSegLatency(parseIntValue(record.get("latency")));
+            PathNode dst = new PathNode();
+            dst.setSwitchId(record.get("dst_switch").asString());
+            dst.setPortNo(parseIntValue(record.get("dst_port")));
+            dst.setSegLatency(parseIntValue(record.get("latency")));
+
+            List<PathNode> pathNodes = new ArrayList<>();
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: (2)? :P

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 13]
```diff
@@ -0,0 +1,166 @@
...
+    public void declareOutputFields(OutputFieldsDeclarer declarer) {
+        declarer.declare(new Fields("response", "correlationId"));
+    }
+
+    @Override
+    public void cleanup() {
+        driver.close();
+    }
+
+    private int parseIntValue(Value value) {
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: It can't handle numeric values stored as strings. There is a lot such objects in DB.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 14]
```diff
@@ -0,0 +1,166 @@
...
+                    pathNodes,
+                    parseIntValue(record.get("speed")),
+                    state,
+                    parseIntValue(record.get("available_bandwidth"))
+            );
+            isl.setTimestamp(System.currentTimeMillis());
+
+            results.add(isl);
+            LOGGER.info("Result ISL: {}", isl);
+
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: why style check allow empty line here?..

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java [hunk 15]
```diff
@@ -0,0 +1,166 @@
...
+        }
+        return results;
+    }
+
+    @Override
+    public void declareOutputFields(OutputFieldsDeclarer declarer) {
+        declarer.declare(new Fields("response", "correlationId"));
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: I prefer to make some object to keep/pass request context - now it is correlationId. Later we can add more field there. If we don't use a "context" object and pass all required fields in "tuples" each new filed in context will lead to change in all interbolt streams (add new field there) and all methods that build output tuples.

If it will be object - to add new field we should add field to object, modify one bolt/spout that construct this object in first place...

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java [hunk 16]
```diff
@@ -0,0 +1,89 @@
...
+            CommandData data = command.getData();
+
+            if (data instanceof BaseRequest) {
+                LOGGER.debug("Processing request with correlationId {}", message.getCorrelationId());
+
+                BaseRequest baseRequest = (BaseRequest) data;
+                processRequest(baseRequest, message.getCorrelationId());
+            }
+        } else {
+            LOGGER.debug("Received unexpected message with correlationId: {}", message.getCorrelationId());
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java]: unhandledInput() ?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java [hunk 17]
```diff
@@ -0,0 +1,89 @@
...
+        }
+    }
+
+    private void processRequest(BaseRequest request, String correlationId) {
+        if (request instanceof SwitchesBaseRequest) {
+            getOutput().emit(StreamType.SWITCH.toString(), Lists.newArrayList(request, correlationId));
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java]: `new Fields(request, correlationId)` instead of `Lists.newArrayList(request, correlationId)`

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java [hunk 18]
```diff
@@ -0,0 +1,116 @@
...
+        this.neoAuth = neoAuth;
+    }
+
+    @Override
+    public void prepare(Map stormConf, TopologyContext context, OutputCollector collector) {
+        this.driver = neoAuth.getDriver();
+        super.prepare(stormConf, context, collector);
+    }
+
+    protected void handleInput(Tuple input) {
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java]: You should move common part that manage tuple unpacking and session management into base class (not AbstractBolt, create new intermediate one).

parseIntValue and similar methods should be moved into base class too.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java [hunk 19]
```diff
@@ -0,0 +1,116 @@
...
+        try (Session session = driver.session(request.isReadRequest() ? AccessMode.READ : AccessMode.WRITE)) {
+            List result = null;
+            if (request instanceof GetSwitchesRequest) {
+                result = getSwitches(session);
+            } else {
+                LOGGER.warn("Received unsupported Switches request: {}", correlationId);
+            }
+
+            LOGGER.debug("Processed read request with correlationId {}", correlationId);
+            getOutput().emit(Lists.newArrayList(result, correlationId));
```
Comment (surabujin) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java]: Fields()

**Comment by surabujin** [comment]
@nikitamarchenko @nikitacherevko Due to introducing AbstractException - this change affect all storm topologies, not only listen in tags now.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java (hunk 17 above)
Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/RouterBolt.java]: it make no sense, because this constructor accepts only String values (and under the hood it still creates new list of this fields)

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java (hunk 15 above)
Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java]: Agree

File: services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java [hunk 20]
```diff
@@ -0,0 +1,95 @@
...
+                + "sw.name as name, "
+                + "sw.address as address, "
+                + "sw.hostname as hostname, "
+                + "sw.description as description, "
+                + "sw.controller as controller, "
+                + "sw.state as state");
+        List<SwitchInfoData> results = new ArrayList<>();
+        for (Record record : result.list()) {
+            SwitchInfoData sw = new SwitchInfoData();
+            sw.setSwitchId(record.get("name").asString());
```
Comment (nikitamarchenko) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java]: Can get NPE here

Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java]: nope, record.get("name") returns Value object in any case
