### PR TITLE
Fix the missing cache errors in Stats caused by partial flow updates

### LINKED ISSUE #4246: Missed cache during partial flow update
**Steps to reproduce:**
1. Create a flow
2. Update flow src or dst port/vlan/inner_vlan

**Expected result:**
**no** messages `Missed cache for switch **** cookie *****` in logs

**Actual result:**
`Missed cache for switch **** cookie ***** messages` in logs

**Reason:**
As we updated just src/dst port/vlan/inner_vlan Kilda wouldn't reallocate flow resources (including cookies). Kilda will just reinstall ingress rules on switch with the same cookie. Let ingress rule has cookie `123`:
1. Kilda install new ingress rule with new port and cookie `123`.
2. Stats topology catch Install command and add cookie `123` to the cache (but this cookie already in cache).
3. Kilda remove old ingress rule with old port and same cookie `123`
4. Stats topology catch remove command and remove cookie `123` from the cache
5. We have installed rule `123` on switch and missed cookie `123` in Stats cache

### PR DESCRIPTION
**Pull request by sergii-iakovenko**
Resolves #4246

### CODE REVIEW

**Review by dpoltavets — APPROVED** [review]

File: src-java/stats-topology/stats-storm-topology/src/main/java/org/openkilda/wfm/topology/stats/MeasurePointKey.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+    }
+
+    public static MeasurePointKey buildForOneSwitchRule(SwitchId switchId, int inPort, int inVlan,
+                                                        int inInnerVlan, int outPort, int outVlan,
+                                                        int outInnerVlan) {
+        return new MeasurePointKey(switchId, inPort, inVlan, inInnerVlan, outPort, outVlan, outInnerVlan);
+    }
+
+    /**
+     * Match the current and provided keys using only set (non-null) fields.
```
Comment (niksv) [inline src-java/stats-topology/stats-storm-topology/src/main/java/org/openkilda/wfm/topology/stats/MeasurePointKey.java:57]: Is it okay that you check only non-null fields? In this case Full port flow will be equal to flow with vlans on the same port

Comment (sergii-iakovenko) [reply src-java/stats-topology/stats-storm-topology/src/main/java/org/openkilda/wfm/topology/stats/MeasurePointKey.java:57]: Full port flows have 0 (zero) vlan, not null. Also all buildXXX methods in the class doesn't accept nulls.

**Review by niksv — APPROVED** [review]

File: src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/FlowStatSpec.groovy [hunk 2]
```diff
@@ -466,7 +466,95 @@ class FlowStatSpec extends HealthCheckSpecification {
...
+    @Tidy
+    def "System is able to collect stats after partial updating(inner vlan) on a flow endpoint"() {
+        given: "Two active neighboring switches connected to the traffgens"
+        def traffGenSwitches = topology.activeTraffGens*.switchConnected*.dpId
+        def switchPair = topologyHelper.switchPairs.find {
+            [it.src, it.dst].every { it.dpId in traffGenSwitches }
+        } ?: assumeTrue(false, "No suiting switches found")
+
+        and: "A flow with updated inner vlan on src endpoint via partial update"
+        def traffgenPortOnSrcSw = topology.activeTraffGens.find { it.switchConnected ==  switchPair.src}.switchPort
```
Comment (andriidovhan) [inline src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/FlowStatSpec.groovy:543]: it is needless, you can create a flow on a traffgen port using the `randomFlow` method.
By default `randomFlow` tries to create a flow on the mentioned port.
```
  FlowRequestV2 randomFlow(SwitchPair switchPair, boolean useTraffgenPorts = true,
            List<FlowRequestV2> existingFlows = []) 
```
If you want explicitly set it, just `flowHelperV2.randomFlow(switchPair, true).tap {  it.source.vlanId = 100}`

**Review by andriidovhan — APPROVED** [review]

**Review by dpoltavets — APPROVED** [review]
