### PR TITLE
Fixed path search with max latency over under-maintenance isls

### LINKED ISSUE #4927: Flow with `max_latency` strategy can't be created on ISL in under_maintenance mode
**Steps to reproduce:**
1. Enable under_maintenance mode on all possible ISLs (on local end you can just run `update isl set under_maintenance=true` in Oriend DB)
2. Try to create flow with `path_computation_strategy=max_latency` and `max_latency` which is less than `isl.cost.when.under.maintenance` (10000 by default) 

```
{
  "flow_id": "flow3",
  "source": {
    "inner_vlan_id": 0,
    "port_number": 10,
    "switch_id": "2",
    "vlan_id": 272
  },
  "destination": {
    "inner_vlan_id": 0,
    "port_number": 10,
    "switch_id": "9",
    "vlan_id": 485
  },
  "max_latency": 1000,
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "path_computation_strategy": "max_latency"
}
```

**Expected result:**
Flow is created

**Actual result:**
Path not found, because under_maintenance penalty is bigger than max_weight of a path, which is equal to max_latency value

P.S. If you will change strategy to cost or latency - flow will be created

### LINKED ISSUE #4986: Can't create Y flow with max_latency strategy and small max_latency value
**Steps to reproduce:**
1. Find 3 switches to create Y flow with following topology:
```
A-------Z-------B
```
2. Choose some max_latency which can be fit for this Y flow. (for example 100 ms)
3. Create Y flow with strategy `max_latency` and chosen `max_latency` (100 ms)

request example for local env
```
{
  "y_flow_id": "flow1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "3"
  },
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
"path_computation_strategy": "max_latency",
"max_latency": 100,
  "sub_flows": [
    {
      "flow_id": "sub1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "4",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
{
      "flow_id": "sub2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "9",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```

**Expected result:**
Y flow is created

**Actual result:**
Resource allocation error

The reason:
Y flow tries to create sub paths close to each other. It's called affinity flows.
To do it path computation engine adds penalty to ISLs which are not belong to sub flow 1 while creating sub flow 2.
Because of this penalty sub flow 2 path can't fin into max_latency requirements.

### PR DESCRIPTION
**Pull request by Nexgen90**
Refactored PathWeight-class for storing penalties separately.
Fixed findPathWithWeightCloseToMaxWeight-method for avoid penalties while desired path is not found.

Closes #4927
Closes #4986

### CODE REVIEW

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java [hunk 1]
```diff
@@ -448,33 +449,72 @@ private SearchNode getDesiredPath(Node start, Node end, WeightFunction weightFun
...
                 // We found the destination
-                if (shiftedCurrentWeight < desiredWeight && current.parentWeight.toLong() < maxWeight) {
+                if (current.parentWeight.getBaseWeight() < maxWeight) {
                     // We found a best path. If we don't get here, then the entire graph will be
                     // searched until we run out of nodes or the depth is reached.
-                    desiredWeight = shiftedCurrentWeight;
-                    desiredPath = current;
+                    if (currentPathWeight.getPenaltyValue(PathWeight.Penalty.DIVERSITY_ISL_LATENCY) > 0
+                            || currentPathWeight.getPenaltyValue(PathWeight.Penalty.DIVERSITY_SWITCH_LATENCY) > 0
+                            || currentPathWeight.getPenaltyValue(PathWeight.Penalty.DIVERSITY_POP_ISL_COST) > 0) {
```
Comment (niksv) [inline src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java:462]: I'm not sure about this `if`

Could you please add tests with this penalties and check that results are same with previous behavior?

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java [hunk 2]
```diff
@@ -15,78 +15,112 @@
...
-            long second = o.params.get(i).longValue();
-            if (first != second) {
-                return first > second ? 1 : -1;
-            }
-            i++;
+        if (getTotalWeight() != o.getTotalWeight()) {
+            return getTotalWeight() > o.getTotalWeight() ? 1 : -1;
         }
+
+        if (!Objects.equals(alternativeBaseWeight, o.getAlternativeBaseWeight())) {
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java:104]: Because in a previous iteration an alternativeBaseWeight variable was as reference type so I had to avoid NPE

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java [hunk 3]
```diff
@@ -15,78 +15,112 @@
...
+
+    public PathWeight(long baseWeight, Long alternativeBaseWeight) {
+        this.baseWeight = baseWeight;
+        this.alternativeBaseWeight = alternativeBaseWeight;
+    }
+
+    public PathWeight(long baseWeight, Map<Penalty, Long> penalties, Long alternativeBaseWeight) {
+        this.baseWeight = baseWeight;
+        this.penalties.putAll(penalties);
+        this.alternativeBaseWeight = alternativeBaseWeight;
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java:54]: Fixed

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java]: Fixed

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java [hunk 4]
```diff
@@ -15,78 +15,112 @@
...
+    /**
+     * Summarize two PathWeights.
+     */
+    public PathWeight add(PathWeight toAdd) {
+        long baseWeightResult = baseWeight + toAdd.getBaseWeight();
+        long alternativeBaseWeightResult = alternativeBaseWeight + toAdd.alternativeBaseWeight;
+        Map<Penalty, Long> penaltiesResult = new EnumMap<>(penalties);
+        toAdd.penalties.forEach((k, v) -> {
+            Long value = penaltiesResult.get(k);
+            long result = Optional.ofNullable(value).orElse(0L) + v;
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java]: Fixed

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java (hunk 1 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java]: Sure! Tests were added and logic changed a bit.

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java [hunk 5]
```diff
@@ -15,78 +15,108 @@
...
 /**
  * Vector path weight representation. Each value in vector corresponds to some path param defined
  * by {@link WeightFunction}. Only PathWeights created by one WeightFunction should be added and compared.
  */
+@ToString
 public class PathWeight implements Comparable<PathWeight> {
 
-    private List<Long> params;
+    private final long baseWeight;
+    private final long alternativeBaseWeight;
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/model/PathWeight.java:32]: I don't know a better name for it ;)
In case of "weightByCostAndAvailableBandwidth" we have to hold alternative parameter for correct comparation.

Please see the compareTo-method:
First of all, it checks `getTotalWeight` (baseWeight + all penalties, but without alternativeBaseWeight)
and if both weights are the same, then it checks `alternativeBaseWeight` (without baseWeight and penalties).

This behaviour checked by tests and I just reproduce this logic in term of new words.

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java [hunk 6]
```diff
@@ -223,48 +232,109 @@ private WeightFunction getWeightFunctionByStrategy(PathComputationStrategy strat
     }
 
     private PathWeight weightByCost(Edge edge) {
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java:237]: We have discussed it with @niksv and decided to keep here.
However I also remove duplicated `weightByLatency` code.

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 7]
```diff
@@ -0,0 +1,370 @@
...
+
+        List<IslImmutableView> isls = new ArrayList<>();
+        isls.addAll(getBidirectionalIsls(switchA, 1, switchB, 2));
+        isls.addAll(getBidirectionalIsls(switchB, 3, switchC, 4));
+
+        List<PathSegment> forwardSegments = new ArrayList<>();
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchA).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchB).srcPort(10)
+                .destSwitch(switchC).destPort(10).build());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:121]: switch B has 2 path segments in port 10. A-B and B-C. looks strange

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 8]
```diff
@@ -0,0 +1,370 @@
...
+                .pathId(FORWARD_PATH_ID)
+                .segments(forwardSegments)
+                .build();
+        when(flowPathRepository.findById(FORWARD_PATH_ID)).thenReturn(java.util.Optional.of(forwardPath));
+
+
+        List<PathSegment> reverseSegments = new ArrayList<>();
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchC).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchB).srcPort(10)
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:135]: same

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 9]
```diff
@@ -0,0 +1,370 @@
...
+        assertEquals(2, availableNetwork.getSwitch(switchB.getSwitchId()).getDiversityGroupUseCounter());
+
+        // check found path
+        PathComputer pathComputer = new InMemoryPathComputer(
+                availableNetworkFactory, new BestWeightAndShortestPathFinder(200), config);
+
+        GetPathsResult path = pathComputer.getPath(flow);
+        assertThat(path, is(notNullValue()));
+        assertThat(path.getForward(), is(notNullValue()));
+        assertThat(path.getReverse(), is(notNullValue()));
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:173]: maybe we should check switches in the path? Path can contain empty segments for example and test will path

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 10]
```diff
@@ -0,0 +1,370 @@
...
+        isls.addAll(getBidirectionalIsls(switchA, 1, switchB, 2));
+        isls.addAll(getBidirectionalIsls(switchB, 3, switchC, 4));
+        isls.addAll(getBidirectionalIsls(switchD, 5, switchB, 6));
+        isls.addAll(getBidirectionalIsls(switchB, 7, switchE, 8));
+
+        List<PathSegment> forwardSegments = new ArrayList<>();
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchA).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchB).srcPort(10)
+                .destSwitch(switchC).destPort(10).build());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:195]: port 10 for 2 segments

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 11]
```diff
@@ -0,0 +1,370 @@
...
+                .segments(forwardSegments)
+                .build();
+        when(flowPathRepository.findById(FORWARD_PATH_ID)).thenReturn(java.util.Optional.of(forwardPath));
+
+
+        List<PathSegment> reverseSegments = new ArrayList<>();
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchC).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchB).srcPort(10)
+                .destSwitch(switchA).destPort(10).build());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:210]: port 10 for 2 segments

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 12]
```diff
@@ -0,0 +1,370 @@
...
+        assertEquals(2, availableNetwork.getSwitch(switchB.getSwitchId()).getDiversityGroupUseCounter());
+
+        // check found path
+        PathComputer pathComputer = new InMemoryPathComputer(
+                availableNetworkFactory, new BestWeightAndShortestPathFinder(200), config);
+
+        GetPathsResult path = pathComputer.getPath(flow);
+        assertThat(path, is(notNullValue()));
+        assertThat(path.getForward(), is(notNullValue()));
+        assertThat(path.getReverse(), is(notNullValue()));
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:247]: Please check switches inside

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 13]
```diff
@@ -0,0 +1,370 @@
...
+        // check found path
+        PathComputer pathComputer = new InMemoryPathComputer(
+                availableNetworkFactory, new BestWeightAndShortestPathFinder(200), config);
+
+        GetPathsResult path = pathComputer.getPath(flow);
+        assertThat(path, is(notNullValue()));
+        assertThat(path.getForward(), is(notNullValue()));
+        assertThat(path.getForward().getSegments().size(), is(4));
+        assertThat(path.getReverse(), is(notNullValue()));
+        assertThat(path.getReverse().getSegments().size(), is(4));
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:323]: I think it's better to check switch ids

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java [hunk 14]
```diff
@@ -0,0 +1,370 @@
...
+                .srcSwitch(switchC)
+                .destSwitch(switchA)
+                .pathId(REVERSE_PATH_ID)
+                .segments(reverseSegments)
+                .build();
+        when(flowPathRepository.findById(REVERSE_PATH_ID)).thenReturn(java.util.Optional.of(reversePath));
+
+        Flow flow = getFlow();
+        flow.setSrcSwitch(switchA);
+        flow.setDestSwitch(switchC);
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:148]: hint: you can add src/dst switches as parameters for geFlow()

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java [hunk 15]
```diff
@@ -0,0 +1,197 @@
...
+         *
+         *   All ISLs are in under-maintenance mode
+         */
+        addBidirectionalLink(network, SWITCH_ID_1, SWITCH_ID_2, 1, 2, true, 5);
+        addBidirectionalLink(network, SWITCH_ID_2, SWITCH_ID_3, 5, 6, true, 5);
+
+        FindPathResult path = pathFinder.findPathWithWeightCloseToMaxWeight(network, SWITCH_ID_1, SWITCH_ID_3,
+                weightFunction, 100, 100);
+
+        assertThat(path, is(notNullValue()));
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java:70]: please check switch ids in path

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java [hunk 16]
```diff
@@ -0,0 +1,498 @@
...
+
+        List<IslImmutableView> isls = new ArrayList<>();
+        isls.addAll(getBidirectionalIsls(switchA, 1, switchB, 2));
+        isls.addAll(getBidirectionalIsls(switchB, 3, switchC, 4));
+
+        List<PathSegment> forwardSegments = new ArrayList<>();
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchA).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        forwardSegments.add(PathSegment.builder().pathId(FORWARD_PATH_ID).srcSwitch(switchB).srcPort(10)
+                .destSwitch(switchC).destPort(10).build());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:119]: same port 10 for 2 ISLs

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java [hunk 17]
```diff
@@ -0,0 +1,498 @@
...
+                .segments(forwardSegments)
+                .build();
+        when(flowPathRepository.findById(FORWARD_PATH_ID)).thenReturn(java.util.Optional.of(forwardPath));
+
+
+        List<PathSegment> reverseSegments = new ArrayList<>();
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchC).srcPort(10)
+                .destSwitch(switchB).destPort(10).build());
+        reverseSegments.add(PathSegment.builder().pathId(REVERSE_PATH_ID).srcSwitch(switchB).srcPort(10)
+                .destSwitch(switchA).destPort(10).build());
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:134]: same

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java [hunk 18]
```diff
@@ -0,0 +1,498 @@
...
+                availableNetworkFactory, new BestWeightAndShortestPathFinder(200), config);
+
+        GetPathsResult path = pathComputer.getPath(flow, Collections.emptyList(), true);
+
+        assertThat(path, is(notNullValue()));
+        assertThat(path.getForward(), is(notNullValue()));
+        assertThat(path.getForward().getSegments().size(), is(3));
+        assertThat(path.getReverse(), is(notNullValue()));
+        assertThat(path.getReverse().getSegments().size(), is(3));
+    }
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:303]: please check switch ids

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java [hunk 19]
```diff
@@ -0,0 +1,498 @@
...
+                availableNetworkFactory, new BestWeightAndShortestPathFinder(200), config);
+
+        GetPathsResult path = pathComputer.getPath(flow, Collections.emptyList(), true);
+
+        assertThat(path, is(notNullValue()));
+        assertThat(path.getForward(), is(notNullValue()));
+        assertThat(path.getForward().getSegments().size(), is(3));
+        assertThat(path.getReverse(), is(notNullValue()));
+        assertThat(path.getReverse().getSegments().size(), is(3));
+        assertThat(path.isBackUpPathComputationWayUsed(), is(true));
```
Comment (niksv) [inline src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:377]: please check switch ids

**Review by niksv — CHANGES_REQUESTED** [review]

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java [hunk 20]
```diff
@@ -0,0 +1,197 @@
...
+        List<Edge> forwardPath = path.getFoundPath().getLeft();
+        assertThat(forwardPath.get(forwardPath.size() - 1).getSrcSwitch().getSwitchId(), is(SWITCH_ID_4));
+    }
+
+    private PathWeight weightByLatency(Edge edge) {
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java]: Fixed

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java [hunk 21]
```diff
@@ -367,7 +368,8 @@ private List<Edge> getPath(Node start, Node end, WeightFunction weightFunction)
 
         while (!toVisit.isEmpty()) {
             SearchNode current = toVisit.pop();
-            log.trace("Going to visit node {} with weight {}.", current.dstSw, current.getParentWeight().toLong());
+            log.trace("Going to visit node {} with weight {}.",
+                    current.dstSw, current.getParentWeight().getTotalWeight());
```
[the remark this answers is not in the document]
Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/finder/BestWeightAndShortestPathFinder.java:372]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java (hunk 7 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java (hunk 19 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:377]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java (hunk 16 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:119]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java (hunk 15 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/FindPathWithLatencyLimitsTest.java]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java (hunk 9 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:188]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java (hunk 8 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/DiversityPathFinderTest.java:138]: Fixed

File: src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java (hunk 18 above)
Comment (Nexgen90) [reply src-java/kilda-pce/src/test/java/org/openkilda/pce/finder/ProtectedPathFinderTest.java:328]: Fixed

File: src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java [hunk 22]
```diff
@@ -223,48 +236,116 @@ private WeightFunction getWeightFunctionByStrategy(PathComputationStrategy strat
...
+            penalties.put(DIVERSITY_SWITCH_LATENCY, (long) value);
+        }
+
+        if (edge.getAffinityGroupUseCounter() > 0) {
+            long value = edge.getAffinityGroupUseCounter() * config.getAffinityIslCost();
+            penalties.put(AFFINITY_ISL_LATENCY, value);
+        }
+
+        long cost = edge.getCost() == 0 ? config.getDefaultIslCost() : edge.getCost();
+        return new PathWeight(cost, penalties, edge.getAvailableBandwidth());
```
Comment (niksv) [inline src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java:348]: we have a lot all duplicate code in weight functions. Maybe we should move common penalties to some common method?

Comment (Nexgen90) [reply src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java:348]: actually no.

**Review by niksv — APPROVED** [review]
