### PR TITLE
open-kilda-4922 [Kilda GUI] wrong port information on switch port page

### LINKED ISSUE #4922: [Kilda GUI] wrong port information on switch port page
**Steps to reproduce:**

1. On tab 1 open port information about switch port `{host}/openkilda/switches/details/{switch_1}/port/{port_1}`
2. On tab 2 open port information about port of some other switch `{host}/openkilda/switches/details/{switch_2}/port/{port_2}`
3. Go to tab 1 and refresh the page.

**Expected result:**
page with information about switch_1 and port_1

**Actual result:**
page about switch_1 and port_1 contains information about switch_2 and port_2

### PR DESCRIPTION
**Pull request by IvanChupin**
fixes
Slightly change the logic for localStorage variables.
switchDetailsJson, portDataObject

closes #4922

### CODE REVIEW

**Review by pablomuri — COMMENTED** [review]
Could you please separate the code formatting and the actual change in two commits? It's a bit difficult to review in this way.

**Review by niksv — APPROVED** [review]

File: src-gui/ui/src/app/modules/switches/port-graph/port-graph.component.ts [hunk 1]
```diff
@@ -8,6 +8,7 @@ import { LoaderService } from 'src/app/common/services/loader.service';
 import { IslDataService } from 'src/app/common/services/isl-data.service';
 import { CommonService } from 'src/app/common/services/common.service';
 import { MessageObj } from 'src/app/common/constants/constants';
+import {ActivatedRoute} from '@angular/router';
```
Comment (dmitrii-beliakov) [inline src-gui/ui/src/app/modules/switches/port-graph/port-graph.component.ts:11]: spaces near the curly braces would be nice as it is in other places. 
The same in other places

**Review by dmitrii-beliakov — APPROVED** [review]

**Review by gauravchug — APPROVED** [review]

**Review by neeraj890kumar — APPROVED** [review]

**Review by pablomuri — APPROVED** [review]

File: src-gui/ui/src/app/modules/switches/port-graph/port-graph.component.ts (hunk 1 above)
Comment (IvanChupin) [reply src-gui/ui/src/app/modules/switches/port-graph/port-graph.component.ts:11]: thanks, fixed it
