### PR TITLE
Fix flow create v2 issues +retries enhancement

### LINKED ISSUE #2575: issues in POST `/api/v2/flows`
- [x] can't set the 'description' field
- [x] can't create a pinned flow
- [x] system is allowing to create an one-switch flow on an DEACTIVATED switch(this issue is relevant for APIv1 too) #2576
- [x] can't create a flow on an Accton switch API #2460
- [x] can't create a protected flow #2459
- [x] can't specify a diverse flow id
- [x] needless transit vlan is being created #2455 (possibly is not relevant anymore)
- [x] an one-switch flow is not valid when it was created on a deactivated switch #2580 
- [ ] flow create events are not showing in kibana flow crud dashboard
- [x] can't to set the 'proiority' field
- [x] can't set the 'maxLatency' field
- [x] getFlow is not returning the 'diverse-with' field
- [x] POST `/api/v2/flows` is returning 500 instead of 409 in case flow conflict
- [x] able to create a flow on an ISL port(this issue is reproduced when port status is FAILED or MOVED)
- [x] unable to create default and simple flows when they are on the same port
- [x] incorrect priority is setting for cookies of default flow

### PR DESCRIPTION
**Pull request by nikitacherevko**
Closes #2575

---
This change is [Reviewable](https://reviewable.io/reviews/telstra/open-kilda/2632)

### CODE REVIEW

File: services/wfm/src/main/java/org/openkilda/wfm/share/utils/AbstractBaseFsm.java [hunk 1]
```diff
@@ -28,7 +28,7 @@
     protected transient Logger log = makeLog();
 
     @Override
-    protected void afterTransitionCausedException(Object fromState, Object toState, Object event, Object context) {
+    protected void afterTransitionCausedException(S fromState, S toState, E event, C context) {
```
Comment (timofei-durakov) [inline services/wfm/src/main/java/org/openkilda/wfm/share/utils/AbstractBaseFsm.java]: like this so much:-P

File: services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java [hunk 2]
```diff
@@ -60,6 +60,8 @@
 @Getter
 public class InstallIngressRuleCommand extends InstallTransitRuleCommand {
 
+    private static final int DEFAULT_FLOW_PRIORITY = FLOW_PRIORITY - 1;
```
Comment (timofei-durakov) [inline services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java]: let's not duplicate these constants, make them public in switch manager if needed

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopologyConfig.java [hunk 3]
```diff
@@ -45,6 +45,14 @@ default String getKafkaFlowSpeakerWorkerTopic() {
     @Default("10")
     int getCreateSpeakerTimeoutSeconds();
 
+    @Key("create.hub.retries")
+    @Default("10")
+    int getCreateHubRetries();
```
Comment (timofei-durakov) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopologyConfig.java]: why 10? tbh I would prefer lower amount of retries

File: services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRequest.java [hunk 4]
```diff
@@ -15,27 +15,54 @@
...
 import lombok.Value;
 
 @Value
+@JsonNaming(value = SnakeCaseStrategy.class)
+@Builder(toBuilder = true)
 public class FlowRequest extends CommandData {
 
-    @JsonProperty(Utils.PAYLOAD)
-    private FlowDto payload;
+    @NonNull
```
Comment (timofei-durakov) [inline services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRequest.java]: JsonProperty?

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java [hunk 5]
```diff
@@ -59,7 +58,7 @@
     @JsonProperty("ignore_bandwidth")
     private boolean ignoreBandwidth;
 
-    @JsonProperty("periodic-pings")
+    @JsonProperty("periodic_pings")
```
Comment (timofei-durakov) [inline services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java]: will this affect existing API for v1?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/SpeakerWorkerBolt.java [hunk 6]
```diff
@@ -74,6 +74,14 @@ public void onTimeout(String key, Tuple tuple) throws PipelineException {
         service.handleTimeout(key);
     }
 
+    @Override
+    protected void unhandledInput(Tuple input) {
+        if (log.isTraceEnabled()) {
```
Comment (timofei-durakov) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/SpeakerWorkerBolt.java]: why is it trace?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java [hunk 7]
```diff
@@ -66,28 +65,31 @@ public FlowValidateAction(PersistenceManager persistenceManager) {
...
         }
-
-        stateMachine.fireNext(context);
-
         return Optional.empty();
     }
+
+    @Override
+    protected String getGenericErrorMessage() {
+        return "Could not create flow";
```
Comment (timofei-durakov) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java]: why not constant?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java [hunk 8]
```diff
@@ -0,0 +1,298 @@
...
+        } catch (FlowNotFoundException e) {
+            log.debug("{}: {}", getGenericErrorMessage(), e.getMessage());
+            throw new FlowProcessingException(ErrorType.NOT_FOUND, getGenericErrorMessage(),
+                    "Can't find the diverse flow: " + e.getMessage());
+        } catch (FlowAlreadyExistException e) {
+            log.info(e.getMessage(), e);
+            if (stateMachine.isRetryAllowed()) {
+                stateMachine.fire(Event.RETRY);
+
+                //nothing to send as a response because we
```
Comment (timofei-durakov) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java]: because we what?

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/SpeakerWorkerBolt.java (hunk 6 above)
Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/SpeakerWorkerBolt.java]: So as a designed for now both create and reroute "hubs" have their own workers, which are receiving tuples from one spout. Currently, we haven't found a solution for it, so receiving "unexpected" tuples is expected and there is no need to flood logs, but we keep trying to find better solution

File: services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java (hunk 2 above)
Comment (niksv) [reply services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java]: +1

File: services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRequest.java (hunk 4 above)
Comment (niksv) [reply services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRequest.java]: @timofei-durakov it will be added by @JsonNaming

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java (hunk 5 above)
Comment (nikitacherevko) [reply services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java]: thanks, good catch

File: services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java (hunk 2 above)
Comment (nikitacherevko) [reply services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java]: honestly, I don't like the idea to keep such constants in switch manager. We can rather place it somewhere else or come up with another solution. Let's do it in the scope of another ticket/PR?

Comment (timofei-durakov) [reply services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java]: +1 for somewhere else, but I really don't like the same constants in several places.

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java (hunk 5 above)
Comment (dpoltavets) [reply services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java]: This should not affect API v1 because FlowPayload is used for this API. FlowDto is used for messaging.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java (hunk 8 above)
Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java]: fixed

File: services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java (hunk 7 above)
Comment (nikitacherevko) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java]: fixed
