### PR TITLE
Fix switch validate and rules sync on meters unsupported switches

### LINKED ISSUE #2453: Sync switch rules operation fails for OF_12 switches
Trying to sync rules on OF_12 switch results in error
```
{
    "correlation_id": "f67fa316-413e-4e8d-8975-227615a5558c",
    "timestamp": 1559731780092,
    "error-type": "Invalid request parameters",
    "error-message": "Meters are not supported on switch $switchId because of OF version OF_12",
    "error-description": "Not supported: $switchId"
}
```

**Expected:** Sync __rules__ operation should not try to do anything with meters (only sync __switch__ should). Sync rules for OF_12 switch should not end with 'meters' error

### PR DESCRIPTION
**Pull request by IlyaMoiseev**
Closes #2453

### CODE REVIEW

File: services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java [hunk 1]
```diff
@@ -969,13 +970,11 @@ private void dumpMeters(SwitchId switchId, String correlationId, String replyToT
             producerService.sendMessageAndTrack(replyToTopic, correlationId, infoMessage);
         } catch (UnsupportedSwitchOperationException e) {
             String messageString = "Not supported: " + switchId;
-            logger.error(messageString, e);
```
Comment (niksv) [inline services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java]: I think we should left logger

Comment (dpoltavets) [reply services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java]: +1

Comment (IlyaMoiseev) [reply services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java]: This case is not error anymore, add info level logging
