### PR TITLE
Isl deactivates twice on port down event

### LINKED ISSUE #1428: ISL deactivates twice after doing port down
Steps:
1. Bring port down for certain ISL
2. Observe ISL going to FAILED status, observe logs saying 'Deactivate ISL <isl>'
3. Wait for <kilda_discovery_timeout> seconds
4. Observe logs *again* saying 'Deactivate ISL <isl>' due to discovery timeout
**Expected:** Kilda do not do a second 'deactivate' if ISL is already deactivated due to port down.

Known impact: If kilda_discovery_timeout is close to kilda_reroute_throttling_delay_min, the second 'deactivation' may cause an additional reroute event, which will postpone the actual reroute handling for another <kilda_reroute_throttling_delay_min> seconds.

### PR DESCRIPTION
**Pull request by IlyaMoiseev**
Closes #1428

### CODE REVIEW

File: services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java [hunk 1]
```diff
@@ -207,30 +208,34 @@ static IslStatus getStatus(Isl forwardIsl, Isl reverseIsl) {
...
         log.debug("ISL by source endpoint {}_{} discovery failed",
                 isl.getSrcSwitch().getSwitchId(), isl.getSrcPort());
-        transactionManager.doInTransaction(() -> processDiscoveryFailedIsl(isl));
+        return transactionManager.doInTransaction(() -> processDiscoveryFailedIsl(isl));
     }
 
-    private void processDiscoveryFailedIsl(Isl isl) {
-        Collection<Isl> isls = islRepository.findBySrcEndpoint(isl.getSrcSwitch().getSwitchId(), isl.getSrcPort());
+    private boolean processDiscoveryFailedIsl(Isl isl) {
+        IslStatus islStatus = IslStatus.MOVED.equals(isl.getStatus()) ? IslStatus.MOVED : IslStatus.INACTIVE;
```
Comment (sergii-iakovenko) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java]: No need to use equals for enums.

Comment (IlyaMoiseev) [reply services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java]: Fixed
