### PR TITLE
Fix null pointer exception during producing flow dump

### LINKED ISSUE #3552: NullPointerException during 'RevertResourceAllocation'
1. Create a flow
2. Trigger a reroute, but flow fails to reroute (switch unavailable)
3. System tries to revert reroute operation
4. System is unable to install original rules and brings flow down
Kibana logs and history contain null pointer exceptions during this operation:
`RevertResourceAllocationAction failed: null`
`Failed to revert resource allocation`
history: [revert_resources.txt](https://github.com/telstra/open-kilda/files/4799038/revert_resources.txt)

Issue is being reproduced in multiple auto-tests, in particular: `AutoRerouteV2Spec#Flow in 'Down' status is rerouted after switchUp event`
No functional impact observed.
Looks related to #3459 #3467

### PR DESCRIPTION
**Pull request by surabujin**
Close #3552

### CODE REVIEW

File: src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy [hunk 1]
```diff
@@ -563,7 +563,7 @@ class AutoRerouteV2Spec extends HealthCheckSpecification {
                 }
                 sleep(500)
             }
-            assert northboundV2.getFlow(firstFlow.flowId).statusInfo =~ /ISL (.*) become INACTIVE because of FAIL TIMEOUT (.*)/
+            assert northboundV2.getFlow(firstFlow.flowId).statusInfo =~ /ISL (.*) become INACTIVE(.*)/
```
Comment (sergii-iakovenko) [inline src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy:566]: nit: Is it really related to the issue?

File: src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java [hunk 2]
```diff
@@ -65,28 +68,27 @@ public PathInfoData map(FlowPath path) {
...
-            resultList.add(new PathNodePayload(flowPath.getSrcSwitch().getSwitchId(), srcPort,
-                    pathSegments.get(0).getSrcPort()));
-
-            for (int i = 1; i < pathSegments.size(); i++) {
-                PathSegment inputNode = pathSegments.get(i - 1);
-                PathSegment outputNode = pathSegments.get(i);
-
-                resultList.add(new PathNodePayload(inputNode.getDestSwitch().getSwitchId(), inputNode.getDestPort(),
-                        outputNode.getSrcPort()));
+            PathSegment left;
```
Comment (sergii-iakovenko) [inline src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java:81]: 2 questions: 
- How are the changes in this file related to the title "NPE during producting flow dump"?
- What benefits do these changes bring? IMHO, 2 iterators instead of an index are neither shorter nor clearer.

File: src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy (hunk 1 above)
Comment (surabujin) [reply src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy:566]: yes... this is fix from @rtretyak. Without this fix, this test fails.

File: src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java (hunk 2 above)
Comment (surabujin) [reply src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java:81]: The only reason I touch this code is to remove call flow.isForward(flowPath) because this call produces an incorrect answer for "extra/detached" paths (we inject such path now into RevertResourceAllocationAction). All other changes related to this one... I have tried to make it simpler, looks like I have failed this target.

If you insist I will revert iteration by indexes.

File: src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy (hunk 1 above)
Comment (sergii-iakovenko) [reply src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy:566]: Ok

File: src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java (hunk 2 above)
Comment (sergii-iakovenko) [reply src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowPathMapper.java:81]: Got it.

**Review by timofei-durakov — APPROVED** [review]
