### PR TITLE
Fix Y-flow with one-switch flow ping timeout

### LINKED ISSUE #5019: Ping request of Y flow with one switch subflow returns timeout
**Steps to reproduce:**
1. Create Y flow where one subflow is one switch flow
2. Try to ping it

**Expected result:**
Correct response

**Actual result:**
Timeout

### PR DESCRIPTION
**Pull request by pablomuri**
Closes #5019

### CODE REVIEW

**Comment by pablomuri** [comment]
Given a Yflow `flow1` with a one-switch subflow `sub1`and a multi-switch flow `sub2`. The response of the y-flow ping will be: 
```json
{
    "y_flow_id": "flow1",
    "ping_success": false,
    "error": "One sub_flow is one-switch flow",
    "sub_flows": [
        {
            "flow_id": "sub2",
            "forward": {
                "ping_success": true,
                "error": null,
                "latency": 1
            },
            "reverse": {
                "ping_success": true,
                "error": null,
                "latency": 4
            }
        }
    ]
}
```

**Comment by pablomuri** [comment]
I’ve just added an error message, but it is hard to know the exact subflow that would fail in the response constructor because we have got rid of that subflow in previous steps.

I could include this information also in the PingContext, but we emit as many PingContext as multiswitch subflows the yflow has

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java [hunk 1]
```diff
@@ -180,7 +180,9 @@ private YFlowPingResponse buildYFlowPingResponse(Group group) {
                     "Expect exact one Y Flow id in pings group response, got - %s", yFlowIdSet));
         }
 
-        return new YFlowPingResponse(yFlowIdSet.iterator().next(), null, new ArrayList<>(subFlowMap.values()));
+        String error = (subFlowMap.size() & 1) == 1 ? "One sub_flow is one-switch flow" : null;
```
Comment (pkazlenka) [inline src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java:183]: > (subFlowMap.size() & 1) == 1
What is the purpose of this hack? I'd recommend either to move it to private method with meaningful name like 
``` boolean isAnySubflowIsOneSwitch(Map<SubFlow> subFlowMap)``` or to rewrite it without bitshifting. I doubt that the person who will read your code is able to do bitshifting in mind to understand what could be possible cases.

Comment (pablomuri) [reply src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java:183]: This is just an optimised way to check if the size is odd. I was initially using an if instead of a ternary operator and I was including a comment. And, yes, I agree that it is not so readable. I will change it. Thanks

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java [hunk 2]
```diff
@@ -180,7 +180,14 @@ private YFlowPingResponse buildYFlowPingResponse(Group group) {
                     "Expect exact one Y Flow id in pings group response, got - %s", yFlowIdSet));
         }
 
-        return new YFlowPingResponse(yFlowIdSet.iterator().next(), null, new ArrayList<>(subFlowMap.values()));
+        String error = oneSwitchFlowExists(subFlowMap) ? "One sub_flow is one-switch flow" : null;
```
[the remark this answers is not in the document]
Comment (pablomuri) [reply src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java]: done

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java [hunk 3]
```diff
@@ -180,7 +180,14 @@ private YFlowPingResponse buildYFlowPingResponse(Group group) {
                     "Expect exact one Y Flow id in pings group response, got - %s", yFlowIdSet));
         }
 
-        return new YFlowPingResponse(yFlowIdSet.iterator().next(), null, new ArrayList<>(subFlowMap.values()));
+        String error = oneSwitchFlowExists(subFlowMap) ? "One subflow is one-switch flow" : null;
```
Comment (pkazlenka) [inline src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java:183]: 1. Please, be consistent at least with yourself: you have `sub flow` in FlowFetcher:238 and `subflow` here.
2. Please, update functional test as well, otherwise it will start to fail: YFlowPingSpec:84

Comment (pablomuri) [reply src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java]: Sorry, I forgot this. 
Done.
