### PR TITLE
Fight port vs switch dump events race condition

### LINKED ISSUE #3990: ISL rarely may not be properly discovered after port flapping
1. Port down happens and ISL status changes to FAILED
2. Port up happens after ~10 seconds (10s = antiflapCooldown)
**Expected:** ISL status changed to DISCOVERED
**Actual:** ISL status _does_ change to UP for 0.5 seconds but then again changes to DOWN and remains DOWN.
Seems to be a floating issue, not easy to reproduce
Full logs of the related period: 
[elasticsearsh_dump1734.json.gz](https://github.com/telstra/open-kilda/files/5826006/elasticsearsh_dump1734.json.gz)
second appeareance: 
[elasticsearsh_dump1737.json.gz](https://github.com/telstra/open-kilda/files/5826051/elasticsearsh_dump1737.json.gz) `("port event" OR "changed status" OR loggerName: org.openkilda.wfm.topology.network.controller.AntiFlapFsm) AND "00:00:00:00:00:00:00:01_2"`

image

### PR DESCRIPTION
**Pull request by surabujin**
Due to different processing path of network(switch) dump and port status
update events inside floodlightrouter these events can switch their
order. As result ISL attached to such port can unexpectedly flap (on
time up to period of network dump).

Rework processing of port status update notification events "processing
path" into floodlightrouter to make it simmilar to network(switch) dump
"processing path".

Close #3990

### CODE REVIEW

**Review by dpoltavets — APPROVED** [review]

File: src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerToControllerProxyBolt.java [hunk 1]
```diff
@@ -93,14 +93,16 @@ protected void proxyInfoMessage(String key, InfoMessage envelope) {
...
-        } else if (payload instanceof PortInfoData) {
-            proxyOnlyIfActiveRegion(key, envelope, (PortInfoData) payload);
         } else if (payload instanceof IslOneWayLatency) {
             proxyOnlyIfActiveRegion(key, envelope, (IslOneWayLatency) payload);
         } else if (payload instanceof IslBaseLatency) {
             proxyOnlyIfActiveRegion(key, envelope, (IslBaseLatency) payload);
         } else if (payload instanceof ConnectedDevicePacketBase) {
             proxyOnlyIfActiveRegion(key, envelope, (ConnectedDevicePacketBase) payload);
+        } else if (payload instanceof PortInfoData) {
+            log.error(
```
Comment (timofei-durakov) [inline src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerToControllerProxyBolt.java:103]: is it really error level?

**Review by timofei-durakov — APPROVED** [review]

File: src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerToControllerProxyBolt.java (hunk 1 above)
Comment (surabujin) [reply src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerToControllerProxyBolt.java:103]: Yes, it should be error. If this event will arrave into this bolt/handler, something have goes wrong in event routing - PortInfoData must be handled by `SpeakerToNetworkProxyBolt` only.
