### PR TITLE
Fixed updating of Y flow while one subflow is one switch

### LINKED ISSUE #4988: Can't update Y flow if one sub flow is one switch and other one is multi switch
**Steps to repoduse:**
1. Create Y flow where A-end == Z-end and B-end != Z-end
Example: 
```
{
  "y_flow_id": "flow1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "2"
  },
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "sub_flows": [
    {
      "flow_id": "sub1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "9",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
{
      "flow_id": "sub2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```

2. Update the flow by PATCH
```
{
  "maximum_bandwidth": 20000
}
```

**Expected result:**
Flow was updated

**Actual result:**
Time out

### PR DESCRIPTION
**Pull request by niksv**
Closes #4988

### CODE REVIEW

File: src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/update/actions/ValidateYFlowAction.java [hunk 1]
```diff
@@ -145,12 +145,20 @@ protected Optional<Message> performWithResponse(State from, State to, Event even
...
     private String getMainAffinityFlowId(YFlow yFlow) {
         // TODO: maybe we should add filtering of one switch sub flows into method getSubFlows()
-        YSubFlow multiSwitchFlows = yFlow.getSubFlows().stream()
+        YSubFlow flowInAffinityGroup = yFlow.getSubFlows().stream()
+                .filter(sub -> sub.getFlow().getAffinityGroupId() != null)
+                .findAny()
+                .orElse(null);
+        if (flowInAffinityGroup != null) {
+            return flowInAffinityGroup.getFlow().getAffinityGroupId();
+        }
```
Comment (pkazlenka) [inline src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/update/actions/ValidateYFlowAction.java:154]: In this particular case (just two stream elements) I'd do something like 
```
String affinityGroup = yFlow.getSubFlows().stream()
                .mapToString(sub -> sub.getFlow().getAffinityGroupId())
                .filter(affinityGroupId -> affinityGroupId != null)
                .findAny()  //can be replaced by .reduce()
                .collect(joining())
if (affinityGroup != "") {
                    return affinityGroup}
```
This way you call .getFlow().getAffinityGroupId() two times for each validate method call instead of three times depending on success.
Overall, I'd rather see method `String getAffinityGroupId()` in YFlow class.

**Review by pkazlenka — APPROVED** [review]
Mostly ok, but feel free to simplify your code before merging.
