### PR TITLE
Fixed bug with empty vlan stats and set vlans

### LINKED ISSUE #5063: Can't patch flow with empty vlan stats and non zeros src/dst vlans
**Steps to reproduce:**
1. Create a flow with non empty Vlans stats and with 0 src and dst vlans via v2 API `POST /v2/flows`
```json
{
  "flow_id": "flow1",
  "source": {
    "inner_vlan_id": 0,
    "port_number": 10,
    "switch_id": "00:00:00:00:00:00:00:01",
    "vlan_id": 0
  },
  "destination": {
    "inner_vlan_id": 0,
    "port_number": 0,
    "switch_id": "00:00:00:00:00:00:00:02",
    "vlan_id": 0
  },
  "maximum_bandwidth": 10000,
  "statistics": {
    "vlans": [
      1,2,3
    ]
  }
}
```
2. Patch the flow with set vlans and empty stat vlans `PATCH /v2/flows/{flow_id}`
```json
{
  "source": {
    "vlan_id": 15
  },
  "destination": {
     "vlan_id": 17
  },
  "statistics": {
    "vlans": []
  }
}
```

**Expected result:**
Successful response:

**Actual result:**
`To collect vlan statistics you need to set source or destination vlan_id to zero`

### PR DESCRIPTION
**Pull request by niksv**
Closes #5063

### CODE REVIEW

**Review by Fedichk — APPROVED** [review]

File: src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java [hunk 1]
```diff
@@ -250,57 +252,108 @@ public void updateVlanStatisticsTest() throws FlowNotFoundException {
...
+    public void unableToUpdateVlanStatisticsOldVlansSetNewVlansSetTest() throws FlowNotFoundException {
+        rununableToUpdateVlanStatisticsTest(VLAN_1, VLAN_2, VLAN_2, VLAN_3);
+    }
+
+    @Test(expected = IllegalArgumentException.class)
+    public void unableToUpdateVlanStatisticsOldVlansZeroNewVlansSetTest() throws FlowNotFoundException {
+        rununableToUpdateVlanStatisticsTest(0, 0, VLAN_1, VLAN_2);
+    }
+
+    private void rununableToUpdateVlanStatisticsTest(
```
Comment (dmitrii-beliakov) [inline src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java:339]: please fix the camel case here

**Review by dmitrii-beliakov — APPROVED** [review]

File: src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java (hunk 1 above)
Comment (niksv) [reply src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java]: fixed
