### PR TITLE
Fixed updating of one switch Y flow

### LINKED ISSUE #4972: Can't update one switch Y flow
**Steps to reproduce:**
1. create one switch Y flow
```
{
  "y_flow_id": "flow1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "2"
  },
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "sub_flows": [
    {
      "flow_id": "sub1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
{
      "flow_id": "sub2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```
2. update flow bandwidth via PATCH request
```
{
  "maximum_bandwidth": 20000
}
```

**Expected result:**
flow was updated

**Actual result:**
Flow is stuck in "In progress" state

### PR DESCRIPTION
**Pull request by niksv**
Closes #4972

### CODE REVIEW

File: src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/update/actions/ValidateYFlowAction.java [hunk 1]
```diff
@@ -127,10 +127,20 @@ protected Optional<Message> performWithResponse(State from, State to, Event even
...
+        if (subFlow != null) {
+            stateMachine.setMainAffinityFlowId(subFlow.getFlow().getAffinityGroupId());
+        } else {
+            // if there is no multi switch flows we have to use one switch flow
+            YSubFlow oneSwitchSubFlow = yFlow.getSubFlows().stream()
+                    .findAny()
+                    .orElseThrow(() -> new FlowProcessingException(ErrorType.DATA_INVALID,
+                    format("No sub-flows of the y-flow %s were found", yFlowId)));
+            stateMachine.setMainAffinityFlowId(oneSwitchSubFlow.getSubFlowId());
+        }
```
Comment (pkazlenka) [inline src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/update/actions/ValidateYFlowAction.java:143]: I'd move this logic to YFlow and YSubFlow classes. Or even overload the getSubFlows() method. So this part of validator would look like
```
if (yFlow.getSubFlows(/*sameSwitchOnly=*/true)).empty()) {
    flowId = yFlow.getSubFlows().get(0).getFlow().getAffinityGroupId();
else  {
    flowId = yFlow.getSubFlows(/*sameSwitchOnly=*/true).get(0).getSubFlowId;
}
stateMachine.setMainAffinityFlowId(flowId)
```
The names and avoiding NPEs could be missing from snippet above, but I hope the idea is clear.

**Review by pkazlenka — APPROVED** [review]

**Review by Nexgen90 — APPROVED** [review]
