### PR TITLE
[Server42] fix resources leak closes #3797

### LINKED ISSUE #3797: Server42: stats app leaks memory if no server42 flows were created
After ~1h, if no server42 flows are created, the `server42-stats` container runs out of memory.
Steps:
1. Start kilda and just leave it for hour+. Do not create any flows
2. call `docker logs server42-stats`
[server42_stats_oom.zip](https://github.com/telstra/open-kilda/files/5416162/server42_stats_oom.zip)
**Expected:** stats app works just fine
**Actual:** java.lang.OutOfMemoryError: Java heap space

### PR DESCRIPTION
**Pull request by nikitamarchenko**

### CODE REVIEW

**Review by timofei-durakov — APPROVED** [review]

File: src-java/server42/server42-control-server-stub/src/main/java/org/openkilda/server42/control/serverstub/StatsServer.java [hunk 1]
```diff
@@ -87,8 +87,10 @@ public void run() {
                     }
                 }
 
-                if (!flows.isEmpty()) {
-                    server.send(flowBucketBuilder.build().toByteArray());
+                server.send(flowBucketBuilder.build().toByteArray());
+                if (flows.isEmpty()) {
+                    log.info("send ping");
+                } else {
                     log.info("send stats");
```
Comment (surabujin) [inline src-java/server42/server42-control-server-stub/src/main/java/org/openkilda/server42/control/serverstub/StatsServer.java:94]: It will be nice to have a number of sent records here.

File: src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/zeromq/StatsCollector.java [hunk 2]
```diff
@@ -73,9 +73,13 @@ public void run() {
...
         log.info("started with session id {}", sessionId);
         while (!isInterrupted()) {
-            try (Socket server = context.createSocket(ZMQ.PULL)) {
+
+            Socket serverRef = null;
+            try {
+                Socket server = context.createSocket(ZMQ.PULL);
                 server.setReceiveTimeOut(1000);
                 server.connect(connectEndpoint);
+                serverRef = server;
```
Comment (surabujin) [inline src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/zeromq/StatsCollector.java:82]: Can/should it be done on line `Socket server = context.createSocket(ZMQ.PULL);`? I suspect that "some" resource allocation happens inside `.createSocket(...)` call, not only inside `.connect(...)` call.

**Review by surabujin — APPROVED** [review]

File: src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/zeromq/StatsCollector.java (hunk 2 above)
Comment (nikitamarchenko) [reply src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/zeromq/StatsCollector.java]: done
