### PR TITLE
Fix/bandwidth update

### LINKED ISSUE #1068: Path computation ignore ISL available_bandwidth on flow update
Path computation mark "currently occupied by flow" ISL as available for path despite available bandwidth.

Having
 - topology with swA and swB with at least 1 possible path
 - the ISL with lowest available_bandwidth on path from swA to swB have available_bandwidth 1000

When:
 - create flow from swA to swB with bandwidth 900
 - update flow set bandwidth 1100

Then
 - ISL's available_bandwidth become -100

Correct behavior - error on update request.

Related to #919

### PR DESCRIPTION
**Pull request by nikitacherevko**
Closes #1068

### CODE REVIEW

File: services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java [hunk 1]
```diff
@@ -187,61 +190,75 @@ public AvailableNetwork removeSelfLoops() {
...
      */
-    public void addIslsOccupiedByFlow(String flowId) {
+    public void addIslsOccupiedByFlow(String flowId, boolean ignoreBandwidth, long flowBandwidth) {
         String query = ""
-                + "MATCH (src:switch)-[fs:flow_segment{flowid: '" + flowId + "'}]->(dst:switch) "
+                + "MATCH (src:switch)-[fs:flow_segment{flowid: $flow_id}]->(dst:switch) "
                 + "MATCH (src)-[link:isl]->(dst) "
                 + "WHERE src.state = 'active' AND dst.state = 'active' AND link.status = 'active' "
                 + "AND link.src_port = fs.src_port AND link.dst_port = fs.dst_port "
+                + "AND ($ignore_bandwidth = true "
```
Comment (surabujin) [inline services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java]:
```
if(!ignoreBandwitdth) {
    query += "AND ink.available_bandwidth + fs.bandwidth >= $requested_bandwidth ";
}
```
is more correct variant.

At least remove " = true" portion, it should be `"AND ($ignore_bandwidth OR link.available_bandwidth + fs.bandwidth >= $requested_bandwidth"`.

File: services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java [hunk 2]
```diff
@@ -187,61 +190,75 @@ public AvailableNetwork removeSelfLoops() {
...
+                + "OR link.available_bandwidth + fs.bandwidth >= $requested_bandwidth) "
                 + "RETURN link";
 
+        Map<String, Object> parameters = ImmutableMap.of(
```
Comment (surabujin) [inline services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java]: There is some object provided by neo4j dedicated to pass params.
