### PR TITLE
Do not ignore sub flow stats if no Y flow rules on a switch

### LINKED ISSUE #5017: Missed `kilda.flow.packets` metric value for sub flows of Y flows
Kilda do not collect egress stats for Y flow subflows

**Steps to reproduce on local env:**
1. Create Y flow
```
{
  "y_flow_id": "flow_1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "9"
  },
  "maximum_bandwidth": 10000,
  "ignore_bandwidth": true,
  "sub_flows": [
    {
      "flow_id": "sub_1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
{
      "flow_id": "sub_2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "7",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```
2. send some traffic to shared endpoint (subflow: sub_2)
```
curl --location --request POST 'localhost:8288/api/1/traffgen/tg9/address' --header 'Content-Type: application/json' --data-raw '{  
    "address": "192.168.1.5/30",
    "vlan": 789                             
}'
```

```
curl --location --request PUT 'localhost:8288/api/1/traffgen/tg9/address/{traff_gen_id_from_prev_respose}/lldp' --header 'Content-Type: application/json' --data-raw '{
        "mac_address": "e4:1d:2d:a5:f3:ac", 
        "port_number": "e4:1d:2d:a5:f3:ac", 
        "chassis_id": "00:02:03:04:05:00", 
        "time_to_live": 100
}'
```

3. Check `kilda.flow.packets` metric in opentsdb for subflow `sub_2` in forward direction (not rate, but absolute value)

**Expected result:**
growing line

**Actual result:**
No such metric for forward direction
But there is correct metric for:
ingress: `kilda.flow.ingress.packets`
raw egress: `kilda.flow.raw.packets` 

Screenshot from 2022-12-14 16-15-30

### PR DESCRIPTION
**Pull request by niksv**
Closes #5017

### CODE REVIEW

File: src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/NotifyFlowStatsOnNewPathsAction.java [hunk 1]
```diff
@@ -44,9 +44,9 @@ protected void perform(S from, S to, E event, C context, T stateMachine) {
                 .forEach(flowPath -> {
                     Flow flow = flowPath.getFlow();
                     UpdateFlowPathInfo pathInfo = new UpdateFlowPathInfo(
```
Comment (dmitrii-beliakov) [inline src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/NotifyFlowStatsOnNewPathsAction.java:46]: wouldn't it be nice to have a builder with meaningful method names? It's difficult to track on review the correct position of arguments, especially when there are multiple arguments of the same type.

Comment (niksv) [reply src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/NotifyFlowStatsOnNewPathsAction.java:46]: In general - yes. But here I just added one parameter and didn't won't to refactor code to use builder here. 
Also one good thing in constructors - if you will add new param in constructor you will must add it into all constructor calls. Otherwise there will be complication error. In case of builder - you will have null values and NPE in runtime

**Review by dmitrii-beliakov — APPROVED** [review]

File: src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/AllocateYFlowResourcesAction.java [hunk 2]
```diff
@@ -157,9 +160,21 @@ public void perform(S from, S to, E event, C context, T stateMachine) {
...
+                for (YSubFlow subFlow : yFlow.getSubFlows()) {
+                    Flow flow = subFlow.getFlow();
+                    for (FlowPath path : flow.getPaths()) {
+                        subPathList.add(new SubFlowPathInfo(
+                                flow.getFlowId(), path.getCookie(), path.getMeterId(),
+                                FlowPathMapper.INSTANCE.mapToPathNodes(flow, path),
+                                flow.getVlanStatistics(), path.hasIngressMirror(), path.hasEgressMirror()));
+                    }
+                }
+                return subPathList;
```
Comment (pablomuri) [inline src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/AllocateYFlowResourcesAction.java:174]: [minor] I'm wondering if here we can use one of those fancy streams to somehow collect the subPathList. But I don't really know how to do that or if it possible.

File: src-java/kilda-model/src/main/java/org/openkilda/model/Flow.java [hunk 3]
```diff
@@ -395,6 +395,17 @@ public boolean isLooped() {
...
+    /**
+     * Returns Y point switch id.
+     */
+    public SwitchId getYPointSwitchId() {
+        YFlow yFlow = getYFlow();
+        if (yFlow == null) {
+            return null;
+        }
+        return yFlow.getYPoint();
+    }
```
Comment (pablomuri) [inline src-java/kilda-model/src/main/java/org/openkilda/model/Flow.java:407]: [minor], here you can do something like: 

return yFlow == null ? null : yFlow.getYPoint();

File: src-java/stats-topology/stats-messaging/src/main/java/org/openkilda/messaging/info/stats/YFlowStatsInfoFactory.java [hunk 4]
```diff
@@ -38,6 +48,20 @@ public RemoveYFlowStatsInfo produceRemoveYFlowStatsInfo() {
...
+     * right source of rule stats for ingress and egress metrics.
+     */
+    public List<UpdateFlowPathInfo> produceUpdateSubFlowNotification() {
+        List<UpdateFlowPathInfo> result = new ArrayList<>();
+        for (SubFlowPathInfo path : subPaths) {
+            result.add(new UpdateFlowPathInfo(path.flowId, blank.yFlowId, blank.yPointResources.getSwitchId(),
+                    path.cookie, path.meterId, path.pathNodes, path.statVlans, path.ingressMirror, path.egressMirror));
+        }
+        return result;
+    }
```
Comment (pablomuri) [inline src-java/stats-topology/stats-messaging/src/main/java/org/openkilda/messaging/info/stats/YFlowStatsInfoFactory.java:63]: [minor] same regarding java streams

**Review by pablomuri — APPROVED** [review]

**Comment by niksv** [comment]
Thank you for your comments. As all of them are minor I'll fix them later, because this is hot fix
