### PR TITLE
Fix wrong response for delete meter request from api call

### LINKED ISSUE #1733: Kilda doesn't properly report result of "Delete Meter" NB API call
Steps to reproduce:
1. Create a single switch flow
2. Delete a meter from the flow
3. Expected result: meter gets deleted, result with deleted=true is returned.
4. Actual result: meter gets deleted, API returns deleted=false.

### PR DESCRIPTION
**Pull request by Levitan**
Closes #1733

### CODE REVIEW

**Comment by Levitan** [comment]
> Please, remove ignoring of this test https://github.com/telstra/open-kilda/blob/develop/services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/switches/MetersSpec.groovy#L38 to verify your fix.

Updated. Test is passed

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/switches/MetersSpec.groovy [hunk 1]
```diff
@@ -34,7 +32,6 @@ class MetersSpec extends BaseSpecification {
         requireProfiles("hardware")
     }
 
-    @Ignore
     @Issue("https://github.com/telstra/open-kilda/issues/1733")
```
Comment (ylobankov) [inline services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/switches/MetersSpec.groovy]: Please, delete @Issue annotation as well.

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/switches/MetersSpec.groovy [hunk 2]
```diff
@@ -5,9 +5,7 @@ import org.openkilda.functionaltests.helpers.Wrappers
 import org.openkilda.messaging.info.meter.SwitchMeterEntries
 import org.openkilda.testing.Constants
 import org.openkilda.testing.model.topology.TopologyDefinition.Switch
-
```
Comment (ylobankov) [inline services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/switches/MetersSpec.groovy]: Add removed line back.
