### PR TITLE
4991 Updated Grpc Exception Handler

### LINKED ISSUE #4991: GRPC API returns incorrect JSON error response
**Steps to reproduce:**
*****ON HARDWARE ENV*****
1. go to GRPC swagger
2. send some incorrect request. For example try to get logical port for unknown IP 1.1.1.1
```GET /noviflow/1.1.1.1/logicalports```

**Expected result:**
Correct JSON response

**Actual result:**
Concatenation of 2 JSONs which can't be parsed
```
can't parse JSON.  Raw result:

{"timestamp":1667985669923,"error-code":-1,"error-message":"Communication failure - UNAVAILABLE: io exception"}{"timestamp":"2022-11-09T09:21:09.937+0000","status":500,"error":"Internal Server Error","message":"UNAVAILABLE: io exception","path":"/api/v1/noviflow/1.1.1.1/logicalports"}
```

### PR DESCRIPTION
**Pull request by durgakako**
Closes #4991

### CODE REVIEW

**Review by pkazlenka — APPROVED** [review]

**Review by niksv — APPROVED** [review]
Looks good but please:
1. Add `Closes #4991` into description. After merging of the PR github will close bug 4991
2. Add tags `bugfix`, `on review` and `ready for testing`

File: src-java/grpc-speaker/grpc-service/src/main/java/org/openkilda/grpc/speaker/utils/GrpcExceptionHandler.java [hunk 1]
```diff
@@ -57,11 +60,10 @@ public ResponseEntity<Object> handleException(GrpcRequestFailureException ex, We
...
         return makeExceptionalResponse(ex, makeErrorPayload(ex.getCode(), ex.getMessage()), status, request);
     }
-
-    @ExceptionHandler
-    public ResponseEntity<Object> handleException(StatusRuntimeException ex, WebRequest request) {
-        GrpcMessageError body = makeErrorPayload(-1, format("Communication failure - %s", ex.getMessage()));
-        return makeExceptionalResponse(ex, body, HttpStatus.INTERNAL_SERVER_ERROR, request);
+    
+    @ExceptionHandler(StatusRuntimeException.class)
+    public void  handleException(StatusRuntimeException ex, HttpServletResponse response) throws IOException {
```
Comment (niksv) [inline src-java/grpc-speaker/grpc-service/src/main/java/org/openkilda/grpc/speaker/utils/GrpcExceptionHandler.java:65]: minor: 2 spaces between `void` and `handle`

File: src-java/grpc-speaker/grpc-service/src/main/java/org/openkilda/grpc/speaker/utils/GrpcExceptionHandler.java [hunk 2]
```diff
@@ -72,6 +74,7 @@ protected ResponseEntity<Object> handleExceptionInternal(Exception exception, Ob
         return makeExceptionalResponse(exception, error, status, request);
     }
 
+
```
Comment (niksv) [inline src-java/grpc-speaker/grpc-service/src/main/java/org/openkilda/grpc/speaker/utils/GrpcExceptionHandler.java:77]: extra line

**Review by niksv — APPROVED** [review]
