### PR TITLE
Handling RequestRejectedException and proper logging of correlation_id

### LINKED ISSUE #4305: Correlation ID is not logged when northbound gets requested with a malformed url
1. Call any NB api with a double slash `//` typo, provide a meaningful 'correlation_id' header:  `GET <nb_host>/api/v2//flows`
2. Goto Kibana and find a related error
**Expected:** Error description contains the provided correlation_id
**Actual:** Log entry has a `${ctx:correlation_id}` value instead of actual correlation id

### PR DESCRIPTION
**Pull request by sergii-iakovenko**
Resolves #4305

### CODE REVIEW

File: src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
+/* Copyright 2022 Telstra Open Source
```
Comment (pablomuri) [inline src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java:1]: Please, update the year

**Review by pablomuri — CHANGES_REQUESTED** [review]

File: src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java (hunk 1 above)
Comment (durgakako) [reply src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java]: updated to 2023.

**Review by niksv — APPROVED** [review]

**Review by pablomuri — APPROVED** [review]
