### PR TITLE
Fix functional test for logging verification

### LINKED ISSUE #1966: "Check Northbound, Storm and Topology Engine logging" test fails
Reproduced on Jenkins job which runs functional tests.
I could not reproduce it locally.

Test fails with following logs:

```
2019-01-31 14:33:10.935 [INFO] Running org.openkilda.functionaltests.spec.logging.CheckLoggingSpec
2019-01-31 14:33:10.936 2019-01-31T10:33:10,893 INFO  TestDataLoggingExtension:-1 - Running test: Check Floodlight logging
2019-01-31 14:33:11.132 2019-01-31T10:33:11,130 INFO  TestDataLoggingExtension:-1 - Running test: Check Northbound, Storm and Topology Engine logging
2019-01-31 14:36:14.639 2019-01-31T10:36:14,642 INFO  TestDataLoggingExtension:-1 - Running spec: ThrottlingRerouteSpec
2019-01-31 14:36:14.640 [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 183.76 s <<< FAILURE! - in org.openkilda.functionaltests.spec.logging.CheckLoggingSpec
2019-01-31 14:36:14.643 [ERROR] Check Northbound, Storm and Topology Engine logging(org.openkilda.functionaltests.spec.logging.CheckLoggingSpec)  Time elapsed: 183.459 s  <<< FAILURE!
2019-01-31 14:36:14.644 org.spockframework.runtime.ConditionFailedWithExceptionError: 
2019-01-31 14:36:14.645 Condition failed with Exception:
2019-01-31 14:36:14.645 
2019-01-31 14:36:14.646 Wrappers.wait(timeout, 10) { def nbLogs = elastic.getLogs(new ElasticQueryBuilder().setTags(KildaTags.NORTHBOUND). setTimeRange(timeout * 2).setLevel("WARN").build()) def stormLogs = elastic.getLogs(new ElasticQueryBuilder().setTags(KildaTags.STORM_WORKER). setTimeRange(timeout * 2).setLevel("WARN").build()) def tpLogs = elastic.getLogs(new ElasticQueryBuilder().setTags(KildaTags.TOPOLOGY_ENGINE). setTimeRange(timeout * 2).setLevel("INFO").build()) assert nbLogs?.hits?.hits?.any { hit -> hit.source.message.contains(flowId) }: "Northbound should generate an error message about not being able to find a flow" assert stormLogs?.hits?.hits?.any { hit -> hit.source.message.contains(flowId) }: "Storm should generate an error message about not being able to find a flow" assert tpLogs?.hits?.hits?.any { hit -> hit.source.message.contains(switchId.toString()) }: "Topology Engine should generate an info message in case of a switch rules validation event" }
2019-01-31 14:36:14.648 
2019-01-31 14:36:14.648 	at org.openkilda.functionaltests.spec.logging.CheckLoggingSpec.Check Northbound, Storm and Topology Engine logging(CheckLoggingSpec.groovy:46)
2019-01-31 14:36:14.649 Caused by: org.openkilda.functionaltests.helpers.Wrappers$WaitTimeoutException: 
2019-01-31 14:36:14.649 Condition was not satisfied within 180.0 seconds
2019-01-31 14:36:14.650 Failed with exception:
2019-01-31 14:36:14.651 
2019-01-31 14:36:14.651 Condition not satisfied:
2019-01-31 14:36:14.652 
2019-01-31 14:36:14.652 stormLogs?.hits?.hits?.any { hit -> hit.source.message.contains(flowId) }
2019-01-31 14:36:14.653 
2019-01-31 14:36:14.653 Storm should generate an error message about not being able to find a flow
2019-01-31 14:36:14.654 
2019-01-31 14:36:14.654 	at org.openkilda.functionaltests.spec.logging.CheckLoggingSpec.Check Northbound, Storm and Topology Engine logging(CheckLoggingSpec.groovy:46)
2019-01-31 14:36:14.655 
```

### PR DESCRIPTION
**Pull request by ylobankov**
Closes #1966.

### CODE REVIEW

File: services/src/test-library/src/main/java/org/openkilda/testing/Constants.java [hunk 1]
```diff
@@ -25,7 +25,7 @@
     public static final Integer RULES_DELETION_TIME = 5;
     public static final Integer RULES_INSTALLATION_TIME = 5;
     public static final Integer HEARTBEAT_INTERVAL = 10;
-    public static final Integer MAX_DEFAULT_METER_ID = 15;
+    public static final Integer MAX_DEFAULT_METER_ID = 31;
```
Comment (niksv) [inline services/src/test-library/src/main/java/org/openkilda/testing/Constants.java]: Maybe it's better to use `MAX_SYSTEM_RULE_METER_ID` from MeterId class?

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy [hunk 2]
```diff
@@ -33,37 +30,23 @@ class CheckLoggingSpec extends BaseSpecification {
...
-        try {
-            northbound.getFlow(flowId)
-        } catch (HttpClientErrorException e) {
-
-        }
-
-        and: "Rules on a switch are validated"
-        def switchId = topology.activeSwitches.first().dpId
-        northbound.validateSwitchRules(switchId)
+        50.times { northbound.getFlow(flowId) }
```
Comment (rtretyak) [inline services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy]: The `20.times` solution didn't work. I don't think that `50.times` is the way to go here. We should rethink this test/verification. Any other way to check that NB produces logs?

File: services/src/test-library/src/main/java/org/openkilda/testing/Constants.java (hunk 1 above)
Comment (ylobankov) [reply services/src/test-library/src/main/java/org/openkilda/testing/Constants.java]: Will be fixed in #1973. Thanks.

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy (hunk 2 above)
Comment (ylobankov) [reply services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy]: Let's try it. Probably it will work.

Comment (ylobankov) [reply services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy]: 20 is working on virtual env fine. Also checking on hw env.

Comment (ylobankov) [reply services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy]: 20 and 50 are not working on staging. Reworked the test.

File: services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java [hunk 3]
```diff
@@ -86,16 +86,8 @@ public HealthCheck getHealthCheck() {
...
-            return restTemplate.exchange("/api/v1/flows/{flow_id}", HttpMethod.GET,
-                    new HttpEntity(buildHeadersWithCorrelationId()), FlowPayload.class, flowId).getBody();
-        } catch (HttpClientErrorException ex) {
-            if (ex.getStatusCode() != HttpStatus.NOT_FOUND) {
-                throw ex;
-            }
-
-            return null;
-        }
+        return restTemplate.exchange("/api/v1/flows/{flow_id}", HttpMethod.GET,
```
Comment (rtretyak) [inline services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java]: this change may affect atdd-staging

Comment (ylobankov) [reply services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java]: Yes, it definitely will, but atdd-staging is already broken now. We will fix it when fixing atdd-staging.

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy [hunk 4]
```diff
@@ -33,37 +33,41 @@ class CheckLoggingSpec extends BaseSpecification {
...
+        flowExc.rawStatusCode == 404
+        flowExc.responseBodyAsString.to(MessageError).errorMessage.contains(flowErrorMsg)
 
-        then: "Northbound, Storm and Topology Engine should log these actions within 3 minutes"
+        and: "Northbound and Storm should log these actions within 30 seconds"
+        int timeout = 31
         Wrappers.wait(timeout, 10) {
             def nbLogs = elastic.getLogs(new ElasticQueryBuilder().setTags(KildaTags.NORTHBOUND).
-                    setTimeRange(timeout * 2).setLevel("WARN").build())
+                    setTimeRange(timeout * 2).setLevel("ERROR").build())
```
[the remark this answers is not in the document]
Comment (ylobankov) [reply services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy]: These logs are used to find an error message about the switch...
