### PR TITLE
#720: Fixed issue with moving back an ISL

### LINKED ISSUE #720: ISL does not recovery after replug
Have switch A B C, and ISL from A.1 to B.1.

Steps to reproduce:
- unplug ISL from B.1 and plug it into C.1
- ISL A.1 <=> B.1 become inactive
- ISL A.1 <=> C.1 become active (DISCOVERED)
- restore ISL - unplug ISL from C.1 and plug back into B.1
- ISL A.1 <=> C.1 become inactuve
- ISL A.1 <=> B.1 must become active, but it doesn't

Workaround - bounce port A.1 (and or B.1)

### PR DESCRIPTION
**Pull request by nikitacherevko**
Fixes issue with replugging/moving ISL from one switch/port to another.

Closes #720

### CODE REVIEW

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
+import com.fasterxml.jackson.annotation.JsonInclude;
+import com.fasterxml.jackson.annotation.JsonProperty;
+import com.fasterxml.jackson.databind.annotation.JsonSerialize;
+import org.apache.commons.lang3.StringUtils;
+
+import java.io.Serializable;
+import java.util.Objects;
+
+@JsonSerialize
```
Comment (sergii-iakovenko) [inline services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java]: JsonSerialize annotation is redundant if you don't set specific serializer or other serialization aspects.

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java [hunk 2]
```diff
@@ -0,0 +1,251 @@
...
+
+    public String getSrcSwitch() {
+        return srcSwitch;
+    }
+
+    public int getSrcPort() {
+        return srcPort;
+    }
+
+    public String getDstSwitch() {
```
Comment (sergii-iakovenko) [inline services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java]: Why not using lombok Setter/Getter?

File: services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+        this.dstEndpoint = null;
+        this.timeCounter = 0;
+        this.checkInterval = checkInterval;
+        this.maxAttempts = maxAttempts;
+        this.consecutiveFailure = 0;
+        this.consecutiveSuccess = 0;
+    }
+
+    /**
+     * Constructor.
```
Comment (sergii-iakovenko) [inline services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java]: Pls, don't create such useless comments.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java [hunk 4]
```diff
@@ -483,25 +511,45 @@ private void handleIslEvent(Tuple tuple, IslInfoData discoveredIsl) {
...
 
+    private void handleMovedIsl(Tuple tuple, String srcSwitch, int srcPort, String dstSwitch, int dstPort) {
+        NetworkEndpoint dstEndpoint = discovery.getLinkDestination(srcSwitch, srcPort);
+        logger.info("Link is moved from {}_{} - {}_{} to endpoint {}_{}", srcSwitch, srcPort,
+                dstEndpoint.getSwitchDpId(), dstEndpoint.getPortId(), dstSwitch, dstPort);
+
+        PathNode srcNode = new PathNode(srcSwitch, srcPort, 0);
+        PathNode dstNode = new PathNode(dstEndpoint.getSwitchDpId(), dstEndpoint.getPortId(), 1);
+        IslInfoData infoData = new IslInfoData(Lists.newArrayList(srcNode, dstNode), IslChangeType.MOVED);
+        InfoMessage message = new InfoMessage(infoData, System.currentTimeMillis(), UUID.randomUUID().toString());
```
Comment (sergii-iakovenko) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java]: The recent code has correlationId as an argument in handleIslEvent, so you can/should reuse it.

File: services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java [hunk 5]
```diff
@@ -483,25 +511,45 @@ private void handleIslEvent(Tuple tuple, IslInfoData discoveredIsl) {
...
+        passToTopologyEngine(tuple, message);
+
+        // we should send reverse link as well to modify status in TE
+        srcNode = new PathNode(dstEndpoint.getSwitchDpId(), dstEndpoint.getPortId(), 0);
+        dstNode = new PathNode(srcSwitch, srcPort, 1);
+        IslInfoData reverseLink = new IslInfoData(Lists.newArrayList(srcNode, dstNode), IslChangeType.MOVED);
+        message = new InfoMessage(reverseLink, System.currentTimeMillis(), UUID.randomUUID().toString());
```
Comment (sergii-iakovenko) [inline services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java]: The recent code has correlationId as an argument in handleIslEvent, so you can/should reuse it.

File: services/wfm/src/test/java/org/openkilda/wfm/OFEventWfmTest.java [hunk 6]
```diff
@@ -93,6 +102,9 @@ public static void setupOnce() throws Exception {
         ////////
     }
 
+    /**
+     * Clear up everything.
```
Comment (sergii-iakovenko) [inline services/wfm/src/test/java/org/openkilda/wfm/OFEventWfmTest.java]: We should add AfterClass and BeforeClass annotations as exceptions for javadoc check.
