### PR TITLE
Fix kafka producer guaranteed order feature

### LINKED ISSUE #854: FL send all messages to 0 partition of kafka
KafkaTopicOrderDescriptor::isEnabled always True for default topics

### PR DESCRIPTION
**Pull request by surabujin**
Due to error in `is guaranteed order` condition it's result was always
true. And guaranteed order was always enables for all produced messages.

Closes #854

### CODE REVIEW

File: services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ProducerTest.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+import java.util.concurrent.Future;
+
+public class ProducerTest extends EasyMockSupport {
+    private static final String TOPIC = "A";
+
+    private org.apache.kafka.clients.producer.Producer<String, String> kafkaProducer;
+    private Producer subject;
+
+    @Before
+    @SuppressWarnings("unchecked")
```
Comment (sergii-iakovenko) [inline services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ProducerTest.java]: You can put SuppressWarnings on a specific line of code, this will give more context to a reader / maintainer.
