### PR TITLE
Fix possible race condition in get flow by switch operation

### LINKED ISSUE #3603: Unhandled exception in org.openkilda.wfm.topology.nbworker.bolts.FlowOperationsBolt
Sometimes we receive the below exception.
[error11153.txt](https://github.com/telstra/open-kilda/files/4884154/error11153.txt)
search reference:
```
Duplicate key Flow(entityId=22849, flowId=03Jul135507_722_capsicum2093, srcSwitch=Switch(entityId=83, switchId=00:00:00:00:00:00:00:01, status=INACTIVE, socketAddress=/172.18.0.24:40782, hostname=lab_service-1.kilda-controller_default, controller=null, description=Nicira, Inc. OF_13 2.12.0, ofVersion=OF_13, ofDescriptionManufacturer=Nicira, Inc., ofDescriptionHardware=Open vSwitch, ofDescriptionSoftware=2.12.0, ofDescriptionSerialNumber=None, ofDescriptionDatapath=None, features=[RESET_COUNTS_FLAG, GROUP_PACKET_OUT_CONTROLLER, PKTPS_FLAG, METERS, MULTI_TABLE, MATCH_UDP_PORT], underMaintenance=false, timeCreate=null, timeModify=null, pop=null, latitude=0.0, longitude=0.0, street=null, city=null, country=null), destSwitch=Switch(entityId=83, switchId=00:00:00:00:00:00:00:01, status=INACTIVE, socketAddress=/172.18.0.24:40782, hostname...
```

### PR DESCRIPTION
**Pull request by rozdy**
Close #3603

### CODE REVIEW

File: src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java [hunk 1]
```diff
@@ -198,8 +198,10 @@ public Flow getFlow(String flowId) throws FlowNotFoundException {
             flows.addAll(flowRepository.findByEndpointSwitch(switchId));
         }
         // need to return Flows unique by id
+        // Due to possible race condition we can have one flow with different flow paths
+        // In this case we should get the last one
```
Comment (surabujin) [inline src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java:202]: HashSet ... is unordered, how do you propose to define "the last one"?

Comment (rozdy) [reply src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java:202]: Reworked code to remove intermediate set at all.
