### PR TITLE
Fix switch sync to be able to repair misconfigured rules with the same cookie

### LINKED ISSUE #4838: Switch Sync timeout if switch has 2 default rules with same cookie
**Steps to reproduce:**
1. Create excess default rule with existing default cookie. 
OVS: 
```
docker exec -it lab_service-1 bash
ovs-ofctl -O OpenFlow13 add-flow ofsw2 cookie=0x8000000000000002,priority=1,in_port=11,dl_src=00:05:95:41:ec:8c/ff:ff:ff:ff:ff:ff,actions=drop
```
2. validate switch
3. sync switch

**Expected result:**
(Optionally) excess rule after validation
Switch sync removes the rule

**Actual result:**
misconfigured rule
Switch sync timeout

### PR DESCRIPTION
**Pull request by rozdy**
Close #4838

### CODE REVIEW

File: src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/OfBatchHolder.java [hunk 1]
```diff
@@ -146,11 +143,7 @@ public BatchData getByUUid(UUID uuid) {
      * Get speaker data by UUID.
      */
     public SpeakerData getSpeakerDataByUUid(UUID uuid) {
-        return Stream.of(flowsMap.values(), metersMap.values(), groupsMap.values())
-                .flatMap(Collection::stream)
-                .filter(data -> uuid.equals(data.getUuid()))
-                .findFirst()
-                .orElseThrow(() -> new IllegalStateException(format("Can't find speaker data with uuid %s", uuid)));
+        return commandMap.get(uuid).getOrigin();
```
Comment (dpoltavets) [inline src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/OfBatchHolder.java:146]: Is it possible to get NPE here?

Comment (rozdy) [reply src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/OfBatchHolder.java:146]: No, commandMap should contains all uuids present in the batch and this method is called for all uuids in the batch.

**Review by dpoltavets — APPROVED** [review]

**Review by nikitamarchenko — APPROVED** [review]
