### PR TITLE
fix yflow is not created without max_bandwidth bug

### LINKED ISSUE #5039: YFlow is not created without `max_bandwidth`
**Steps to reproduce:**
make test-topology

Try to create a YFlow without max_bandwidth included in the body:
```
HTTP POST http://kilda-vm:8080/api/v2/y-flows
{
  "y_flow_id": "flow1",
  "shared_endpoint": {
    "port_number": 10,
    "switch_id": "1"
  },
  "sub_flows": [
    {
      "flow_id": "sub1",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "2",
        "vlan_id": 123
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 456
      }
    },
    {
      "flow_id": "sub2",
      "endpoint": {
        "inner_vlan_id": 0,
        "port_number": 10,
        "switch_id": "3",
        "vlan_id": 345
      },
      "shared_endpoint": {
        "inner_vlan_id": 0,
        "vlan_id": 789
      }
    }
  ]
}
```
Returns OK.

Get the flow `flow1`:
`HTTP GET http://kilda-vm:8080/v2/y-flows/flow1`

**Expected result:**
`Flow1`info.

**Actual result:**
"Y-flow not found"

NOTE: It has been tested in `develop` and `v1.126.3`.

### PR DESCRIPTION
**Pull request by pablomuri**
Closes #5039

### CODE REVIEW

File: src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java [hunk 1]
```diff
@@ -511,6 +511,11 @@ private List<SpeakerData> buildSharedEndpointYFlowCommands(List<FlowPath> flowPa
         }
         MeterId sharedMeterId = yFlow.getSharedEndpointMeterId();
 
+        if (sharedMeterId == null) {
+            log.debug("Skip commands for the y-flow {} as the sharedMeterId is null", yFlow.getYFlowId());
+            return emptyList();
```
Comment (dmitrii-beliakov) [inline src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java:516]: Are there tests covering these new cases? Require non-null below might throw an exception and now that iteration is skipped, so it's a different behavior

**Review by dmitrii-beliakov — APPROVED** [review]

File: src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java (hunk 1 above)
Comment (niksv) [reply src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java:516]: Line 549 contains code with generator. This generator generates OpenFlow commands. In out case it's meter and rule commands. If we do not have meterId then we should not generate meter commands, but we still must generate rules commands.

You code will successfully create Y flow withput meter, but this flow wouldn't transmit traffic. To check traffic transmission you can one of the following:
1. Create functional tests with traffic generations.
2. Generate traffic manually and look at rules counters and statistics in OpenTSDB. Example: https://github.com/telstra/open-kilda/issues/5017

**Review by niksv — CHANGES_REQUESTED** [review]

File: src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java (hunk 1 above)
Comment (pablomuri) [reply src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java:516]: I was reading the code and thought it was only installing meter commands. In fact, I tried with the ping tool from the API and it works. I will try the traffic transmissions that you propose. Thanks

Comment (niksv) [reply src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java:516]: Ping tool has one disadvantage: during ping it doesn't use ingress (first) and egress (last) rules in flow path. It tests only transit rules because of technical restrictions. As you removed ingress rules - ping was successful

**Review by dmitrii-beliakov — APPROVED** [review]

**Review by niksv — APPROVED** [review]

**Review by artHalMirantis — APPROVED** [review]
