### PR TITLE
Treat the discovery timeout property as a number of ticks

### LINKED ISSUE #807: Incorrect ISL timeout calculation
We got following properties for storm WFM/ET topology:
kilda_discovery_interval: 5
kilda_discovery_timeout: 30
But ET marks ISL as inactive if link is not discovered in about 3 minutes, instead of 30 seconds, as we defined in properties file.
```
May 21st 2018, 20:01:36.647    storm-worker_log    INFO    Link is moved from 00:00:00:00:00:00:00:01_1 - 00:00:00:00:00:00:00:02_1 to endpoint 00:00:00:00:00:00:00:03_1 
May 21st 2018, 20:04:37.530    kilda-tpe    INFO    Deactivate ISL 00:00:00:00:00:00:00:02_1  <===> 00:00:00:00:00:00:00:01_1
```

### PR DESCRIPTION
**Pull request by sergii-iakovenko**
The changes:
- Make OFELinkBolt treating the discovery timeout property as a number of ticks, not as attempts.
- Cleanup in POMs.

Affected components:
- wfm/kilda-wfm

Fixes #807

### CODE REVIEW

File: services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java [hunk 1]
```diff
@@ -128,14 +147,15 @@ public void a_switch_is_dropped_in_the_middle() throws Exception {
...
         // Write code here that turns the phrase above into concrete actions
         throw new PendingException();
     }
 
     @Then("^the links disappear from the topology engine\\.$")
-    public void the_links_disappear_from_the_topology_engine() throws Exception {
-        //todo check whether we need to wait until links will disappear or we might delete them instantly when switch goes down
+    public void theLinksDisappearFromTheTopologyEngine() throws Exception {
+        //todo check whether we need to wait until links will disappear or
+        // we might delete them instantly when switch goes down
```
Comment (surabujin) [inline services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java]: Now we know - we must not remove links on switch `down`. It can be control plane outage of switch reboot or some other switch flapping. In any of this events we should not remove ISLs.

File: services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature [hunk 2]
```diff
@@ -11,15 +11,15 @@ Feature: Basic Topology Events
...
+  @MVP1
   Scenario: Link is Dropped
 
     Given a clean controller
     And a random linear topology of 5 switches
     When the controller learns the topology
     And multiple links exist between all switches
     And a link is dropped in the middle
-    Then the link disappears from the topology engine.
+    Then the link disappears from the topology engine in 60 seconds.
```
Comment (surabujin) [inline services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature]: why so long time?
can it be decreased by config manipulation?

File: services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java (hunk 1 above)
Comment (sergii-iakovenko) [reply services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java]: This is just a checkstyle fix. But I agree that implementation of these test scenarios should align them  with the system design.

File: services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature (hunk 2 above)
Comment (sergii-iakovenko) [reply services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature]: 60 seconds is acceptable time length for discovery events defined in TopologyDiscoveryBasic.feature. 
Sure we can decrease it, but must consider the environment where the tests are to be executed.

File: services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java [hunk 3]
```diff
@@ -64,56 +82,57 @@ public void multiple_links_exist_between_all_switches() throws Exception {
...
-        assertFalse("Link should be cut", cutLinks.isEmpty());
-        assertThat("Only one link should be cut", cutLinks.size(), is(1));
+        manipulatedLinkId = middleLink.getId();
     }
 
-    @Then("^the link disappears from the topology engine\\.$")
-    public void the_link_disappears_from_the_topology_engine() throws Exception {
-        List<IslInfoData> links = LinksUtils.dumpLinks();
+    @Then("^the link disappears from the topology engine in (\\d+) seconds\\.$")
+    public void theLinkDisappearsFromTheTopologyEngine(int timeout) throws Exception {
```
Comment (rtretyak) [inline services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java]: timeout param is not used in the method. How does it influence the test? (same for appear method below)

File: services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature [hunk 4]
```diff
@@ -31,7 +31,7 @@ Feature: Basic Topology Events
     When the controller learns the topology
     And multiple links exist between all switches
     And a link is added in the middle
-    Then the link appears in the topology engine.
+    Then the link appears in the topology engine in 60 seconds.
```
Comment (rtretyak) [inline services/src/atdd/src/test/resources/features/mvp.1/TopologyEventsBasic.feature]: I thought the timeout only applies to the ISL outage, not discovery. Links usually appear right away

File: services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java [hunk 5]
```diff
@@ -64,56 +82,57 @@ public void multiple_links_exist_between_all_switches() throws Exception {
...
+        List<String> cutLinks = Failsafe.with(retryPolicy
+                .retryIf(links -> links instanceof List && ((List) links).isEmpty()))
+                .get(() -> LinksUtils.dumpLinks().stream()
+                        .filter(isl -> isl.getState() != IslChangeType.DISCOVERED)
+                        .map(IslInfoData::getId)
+                        .collect(Collectors.toList())
+                );
```
Comment (rtretyak) [inline services/src/atdd/src/test/java/org/openkilda/atdd/TopologyEventsBasicTest.java]: you should also verify that it took **not less** than `timeout` before link got cut. It also should not take too long. I think  it should be some kind of +- window verification as we did with traffic.
