### PR TITLE
Fix stats test for default rules

### LINKED ISSUE #1929: Functional test "Stats are being logged for metric" fails
This test randomly fails with:

```
2019-01-24 19:44:00.353 [ERROR]   OpenTsdbSpec.Stats for default rules:40 Condition not satisfied:
2019-01-24 19:44:00.355 
2019-01-24 19:44:00.355 otsdb.query(2.minutes.ago, metric, tags).dps.size() > 0
2019-01-24 19:44:00.356 |     |       |       |    |       |     |   |      |
2019-01-24 19:44:00.356 |     |       |       |    |       |     [:] 0      false
2019-01-24 19:44:00.357 |     |       |       |    |       [cookieHex:0x8000000000000003]
2019-01-24 19:44:00.357 |     |       |       |    pen.switch.flow.system.packets
2019-01-24 19:44:00.358 |     |       |       Thu Jan 24 15:41:59 UTC 2019
2019-01-24 19:44:00.358 |     |       2 minutes
2019-01-24 19:44:00.359 |     StatsResult(metric=pen.switch.flow.system.packets, tags={cookieHex=0x8000000000000003}, aggregateTags=[switchid], dps={})
2019-01-24 19:44:00.360 <org.openkilda.testing.service.otsdb.OtsdbQueryServiceImpl@43ec61f0 restTemplate=org.springframework.web.client.RestTemplate@a3a54d6>
2019-01-24 19:44:00.360 
```

### PR DESCRIPTION
**Pull request by rtretyak**
closes #1929

### CODE REVIEW

File: services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/isl/IslMovementSpec.groovy [hunk 1]
```diff
@@ -104,6 +109,15 @@ class IslMovementSpec extends BaseSpecification {
         !islUtils.getIslInfo(allLinks, expectedIsl).present
         !islUtils.getIslInfo(allLinks, islUtils.reverseIsl(expectedIsl)).present
 
+        and: "Self-loop rule packet counter is incremented and logged in otsdb"
+        def statsData = null
+        Wrappers.wait(70, 2) {
```
Comment (ylobankov) [inline services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/isl/IslMovementSpec.groovy]: What about moving 70 to constants? In the future, it will be easier to tune this time.

STATS_LOGGING_TIMEOUT = 70.

Comment (rtretyak) [reply services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/isl/IslMovementSpec.groovy]: done
