### PR TITLE
fix: add ping haflow compatibility in FailReporter

### LINKED ISSUE #5239: Flow ping topology generates NPE when creating HA-flow
**Steps to reproduce:**
1. Create an HA-flow with protected paths
```json
{
    "ha_flow_id": "ha-flow-2",
    "shared_endpoint": {
        "switch_id": "00:00:00:00:00:00:00:02",
        "port_number": 23,
        "vlan_id": 0,
        "inner_vlan_id": 0
    },
    "maximum_bandwidth": 0,
    "path_computation_strategy": "COST",
    "encapsulation_type": "transit_vlan",
    "max_latency": 0,
    "max_latency_tier2": 0,
    "ignore_bandwidth": true,
    "periodic_pings": true,
    "pinned": false,
    "priority": 0,
    "strict_bandwidth": false,
    "description": "HA flow test description 2",
    "allocate_protected_path": true,
    "sub_flows": [
        {
            "endpoint": {
                "switch_id": "00:00:00:00:00:00:00:09",
                "port_number": 22,
                "vlan_id": 0,
                "inner_vlan_id": 0
            },
            "description": "the first end point"
        },
        {
            "endpoint": {
                "switch_id": "00:00:00:00:00:00:00:09",
                "port_number": 21,
                "vlan_id": 0,
                "inner_vlan_id": 0
            },
            "description": "the second end point"
        }
    ]
}
```
2. Check logs

**Espected result:**
no error in logs 

**Actual result:**
`Unhandled exception in org.openkilda.wfm.topology.ping.bolt.FailReporter` in logs

### PR DESCRIPTION
**Pull request by pablomuri**
Closes #5239

### CODE REVIEW

**Review by niksv — APPROVED** [review]

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java [hunk 1]
```diff
@@ -427,7 +428,17 @@ private void emitCacheExpire(Tuple input, CommandContext commandContext, Set<Flo
         OutputCollector collector = getOutput();
         flowsSet.removeAll(flows);
         for (FlowWithTransitEncapsulation flow : flowsSet) {
-            Values output = new Values(flow.getFlow(), commandContext);
+            CacheExpirationRequest cacheExpirationRequest;
+            if (flow.getHaFlow() != null) {
+                cacheExpirationRequest = new CacheExpirationRequest(flow.getHaFlow().getHaFlowId(),
```
Comment (dmitrii-beliakov) [inline src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java:433]: do you also prefer constructors to builders? With a builder it's more clear. But this is just an option

**Review by dmitrii-beliakov — APPROVED** [review]
There is no tests for these changes. Do you consider it trivial? It would be nice to cover with tests the FailReporter

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java (hunk 1 above)
Comment (pkazlenka) [inline src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java:433]: I think the code will be more readable if you add either 
`CacheExpirationRequest(FlowWithTransitEncapsulation flow)`
or `FlowWithTransitEncapsulation(Flow flow)` + `FlowWithTransitEncapsulation(HaFlow haFlow)` constructors.
This would let you avoid copy-pasting `flow.getXFlow()` calls several times.
As an option, `FlowWithTransitEncapsultation.toCacheExpirationRequest()` can play the trick as well.

**Review by pkazlenka — APPROVED** [review]

**Review by durgakako — APPROVED** [review]

File: src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java (hunk 1 above)
Comment (pablomuri) [reply src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java]: done

**Review by pkazlenka — APPROVED** [review]

**Comment by pkazlenka** [comment]
Verified manually.
