### PR TITLE
Skip reroute requests for flows without affected path segment

### LINKED ISSUE #3390: System may not reroute all required flows on ISL Down
**Situation:** high loaded environment, network 'storm' appears, causing a lot of reroutes across the network.
**Problem:** After storm ends and network stabilizes some flows end up in UP state, but on broken ISLs. Neither flow history nor kilda logs show any reroute commands for those flows. Further investigation showed an unhandled exception during reroute of one of the flows that was caused by the 'Isl down' event, the same ISL that has problem not rerouted flows on it. That exception aborted all the scheduled reroutes related to the 'down' event of broken isl. Error: [error.txt](https://github.com/telstra/open-kilda/files/4475619/error.txt).
Full logs dump: I have it, pm me
example of not rerouted flow on broken path: `14Apr122624_282_soyflour0755`

### PR DESCRIPTION
**Pull request by rozdy**
Close #3390

### CODE REVIEW

File: src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java [hunk 1]
```diff
@@ -137,7 +141,13 @@ private void updateFlowPathsStateForFlow(SwitchId switchId, int port, List<FlowP
                         || (pathSegment.getDestPort() == port
                         && switchId.equals(pathSegment.getDestSwitch().getSwitchId()))) {
                     pathSegment.setFailed(true);
-                    pathSegmentRepository.updateFailedStatus(fp.getPathId(), pathSegment, true);
+                    try {
+                        pathSegmentRepository.updateFailedStatus(fp.getPathId(), pathSegment, true);
+                    } catch (EntityNotFoundException e) {
+                        log.warn("FlowPath {} not found. Skipping reroute for flow {}.",
+                                fp.getPathId(), fp.getFlow().getFlowId(), e);
+                        return false;
```
Comment (surabujin) [inline src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java:149]: em... what about the rest of paths passed into `paths` argument? Now you stop processing paths on first error (not so critical as stop processing all flows on the first error, but still incorrect).

File: src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java [hunk 2]
```diff
@@ -98,21 +99,24 @@ public void rerouteAffectedFlows(MessageSender sender, String correlationId, Rer
 
         for (FlowWithAffectedPaths entry : groupPathsForRerouting(affectedFlowPaths)) {
             Flow flow = entry.getFlow();
-            transactionManager.doInTransaction(() -> {
-                updateFlowPathsStateForFlow(switchId, port, entry.getAffectedPaths());
+            Boolean sendRerouteRequest = transactionManager.doInTransaction(() -> {
+                boolean flowPathFound = updateFlowPathsStateForFlow(switchId, port, entry.getAffectedPaths());
```
Comment (surabujin) [inline src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java:103]: swapping this and following lines you can get rid of `flowPathFound` variable.

Comment (rozdy) [reply src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java:104]: I can't swap lines because flow status computation is dependent on flow paths statuses.

File: src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java (hunk 1 above)
Comment (rozdy) [reply src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java]: Reworked.
