### PR TITLE
Fixed incorrect vlan stats create/update

### LINKED ISSUE #5057: Can't patch flow via API /v2/flows/{flow_id} if vlan statis is empty and dst vlan is 0
**Steps to reproduce:**
1. Create flow with src_vlan != 0 and dst_vlan = 0 and non empty stats vlans
2. Patch the flow using API /v2/flows/{flow_id} and body
```json
{
  "statistics": {
    "vlans": []
  }
}  
```

**Expected result:**
Flow will be updated

**Actual result:**
Error: `To collect vlan statistics you need to set source or destination vlan_id to zero`

### LINKED ISSUE #5058: Cant create flow with empty statistics vlans
**Steps to reproduce:**
1. Create flow via API `POST /v2/flows` and empty statistics vlan
```json
{
  "flow_id": "flow3",
  "source": {
    "inner_vlan_id": 0,
    "port_number": 0,
    "switch_id": "2",
    "vlan_id": 1445
  },
  "destination": {
    "inner_vlan_id": 0,
    "port_number": 10,
    "switch_id": "9",
    "vlan_id": 3526
  },
  "maximum_bandwidth": 10000,
  "statistics": {
    "vlans": []
  }
}
```

**Expected result:**
Created flow

**Actual result:**
Error `To collect vlan statistics you need to set source or destination vlan_id to zero`

### PR DESCRIPTION
**Pull request by niksv**
Closes #5057
Closes #5058

### CODE REVIEW

File: src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java [hunk 1]
```diff
@@ -231,6 +233,63 @@ public void shouldUpdateVlanStatistics() throws FlowNotFoundException {
...
+                .vlanStatistics(new HashSet<>())
+                .build();
+        flowRepository.add(flow);
+
+        FlowPatch receivedFlow = FlowPatch.builder()
+                .flowId(FLOW_ID_1)
+                .vlanStatistics(Sets.newHashSet(1, 2, 3))
+                .build();
+
+        flowOperationsService.updateFlow(new FlowCarrierImpl(), receivedFlow);
```
Comment (dmitrii-beliakov) [inline src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java:290]: missing assertion

**Review by dmitrii-beliakov — APPROVED** [review]
